<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>STAT 340: Data Science II - 22&nbsp; Estimation Part 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./estimation2_practice.html" rel="next">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./estimation1.html">Estimation</a></li><li class="breadcrumb-item"><a href="./estimation2.html"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Estimation Part 2</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">STAT 340: Data Science II</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">STAT 340 Index</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false">
 <span class="menu-text">Sampling</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_rv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Probability and Random Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R01_Prob_RVs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Probability and Random Variable R Examples</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rv_practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Probability and Random Variables Practice</span></span></a>
  </div>
</li>
          <li class="px-0"><hr class="sidebar-divider hi "></li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Random Variable Distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R02_Distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Random Variable Distributions R Examples</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cov_practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Independence and Conditional Probability Practice</span></span></a>
  </div>
</li>
          <li class="px-0"><hr class="sidebar-divider hi "></li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Monte Carlo</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R03_MonteCarloExamples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Monte Carlo Examples</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mc_practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Monte Carlo Practice</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R_MonteCarlo_Battleship.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Monte Carlo Battleship</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false">
 <span class="menu-text">Testing</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./testing1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Introduction to Statistical Testing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R04_Monte_Carlo_Testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Monte Carlo Testing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./testing1_practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Monte Carlo Testing Practice</span></span></a>
  </div>
</li>
          <li class="px-0"><hr class="sidebar-divider hi "></li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./testing2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Statistical Testing, Continued</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R05_testing_Additional_Examples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Monte Carlo Testing: Additional Examples</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./testing2_practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Testing and Power Practice</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Estimation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./estimation1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Estimation Part 1</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./estimation1_practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Point Estimation Practice</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R06_More_Estimation_Examples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Estimation Examples</span></span></a>
  </div>
</li>
          <li class="px-0"><hr class="sidebar-divider hi "></li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./estimation2.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Estimation Part 2</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./estimation2_practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Interval Estimation Practice</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R07_More_Estimation_and_CI_Examples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Interval Estimation Examples</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false">
 <span class="menu-text">Prediction</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prediction1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Prediction (Simple Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slr_practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Simple Linear Regression Practice</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R08_prediction_examples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Simple Linear Regression - Examples</span></span></a>
  </div>
</li>
          <li class="px-0"><hr class="sidebar-divider hi "></li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prediction2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Prediction (Multiple Linear Regression)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R09_Multiple_Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">R10 multiple regression further concepts</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlr_practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Multiple Linear Regression Practice</span></span></a>
  </div>
</li>
          <li class="px-0"><hr class="sidebar-divider hi "></li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Logistic Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R10_LogisticReg_Extended.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Logistic Regression - Extended Examples</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistic_practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Logistic Regression Practice</span></span></a>
  </div>
</li>
          <li class="px-0"><hr class="sidebar-divider hi "></li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Model Selection and Cross Validation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R11_cv-MSEcomparison.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">cv-extra</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R11_Bias_Variance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Bias Variance Tradeoff</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R11_Model_Selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">R11 Model Selection</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R11_Ridge_LASSO.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">R11: Ridge and Lasso</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cv_practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Cross Validation Practice</span></span></a>
  </div>
</li>
          <li class="px-0"><hr class="sidebar-divider hi "></li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false">
 <span class="menu-text">Bootstrapping</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bootstrap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Bootstrapping</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R12_Bootstrap_Examples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">R13_Bootstrap</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bootstrap_practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Bootstrap Practice</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./RV_summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Random Variable Summary</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives"><span class="header-section-number">22.1</span> Learning objectives</a></li>
  <li><a href="#recap-estimation-so-far" id="toc-recap-estimation-so-far" class="nav-link" data-scroll-target="#recap-estimation-so-far"><span class="header-section-number">22.2</span> Recap: estimation so far</a>
  <ul class="collapse">
  <li><a href="#example-gone-fishing" id="toc-example-gone-fishing" class="nav-link" data-scroll-target="#example-gone-fishing"><span class="header-section-number">22.2.1</span> Example: gone fishing</a></li>
  </ul></li>
  <li><a href="#enter-confidence-intervals" id="toc-enter-confidence-intervals" class="nav-link" data-scroll-target="#enter-confidence-intervals"><span class="header-section-number">22.3</span> Enter: Confidence intervals</a></li>
  <li><a href="#aside-wait-that-wasnt-a-confidence-interval" id="toc-aside-wait-that-wasnt-a-confidence-interval" class="nav-link" data-scroll-target="#aside-wait-that-wasnt-a-confidence-interval"><span class="header-section-number">22.4</span> Aside: wait, that wasn’t a confidence interval!</a></li>
  <li><a href="#capturing-uncertainty-in-our-estimate" id="toc-capturing-uncertainty-in-our-estimate" class="nav-link" data-scroll-target="#capturing-uncertainty-in-our-estimate"><span class="header-section-number">22.5</span> Capturing uncertainty in our estimate</a></li>
  <li><a href="#okay-but-we-dont-know-mathbbe-s" id="toc-okay-but-we-dont-know-mathbbe-s" class="nav-link" data-scroll-target="#okay-but-we-dont-know-mathbbe-s"><span class="header-section-number">22.6</span> Okay, but we don’t know <span class="math inline">\(\mathbb{E} S\)</span></a>
  <ul class="collapse">
  <li><a href="#example-intervals-for-the-poisson-rate-parameter" id="toc-example-intervals-for-the-poisson-rate-parameter" class="nav-link" data-scroll-target="#example-intervals-for-the-poisson-rate-parameter"><span class="header-section-number">22.6.1</span> Example: Intervals for the Poisson rate parameter</a></li>
  <li><a href="#example-estimating-the-rate-in-the-exponential-distribution" id="toc-example-estimating-the-rate-in-the-exponential-distribution" class="nav-link" data-scroll-target="#example-estimating-the-rate-in-the-exponential-distribution"><span class="header-section-number">22.6.2</span> Example: estimating the rate in the exponential distribution</a></li>
  </ul></li>
  <li><a href="#confidence-intervals-another-way-the-clt" id="toc-confidence-intervals-another-way-the-clt" class="nav-link" data-scroll-target="#confidence-intervals-another-way-the-clt"><span class="header-section-number">22.7</span> Confidence intervals another way: the CLT</a>
  <ul class="collapse">
  <li><a href="#the-clt-in-action" id="toc-the-clt-in-action" class="nav-link" data-scroll-target="#the-clt-in-action"><span class="header-section-number">22.7.1</span> The CLT in action</a></li>
  <li><a href="#using-the-clt-to-build-a-ci" id="toc-using-the-clt-to-build-a-ci" class="nav-link" data-scroll-target="#using-the-clt-to-build-a-ci"><span class="header-section-number">22.7.2</span> Using the CLT to build a CI</a></li>
  <li><a href="#example-confidence-interval-for-the-mean-using-clt" id="toc-example-confidence-interval-for-the-mean-using-clt" class="nav-link" data-scroll-target="#example-confidence-interval-for-the-mean-using-clt"><span class="header-section-number">22.7.3</span> Example: confidence interval for the mean using CLT</a></li>
  </ul></li>
  <li><a href="#which-confidence-interval" id="toc-which-confidence-interval" class="nav-link" data-scroll-target="#which-confidence-interval"><span class="header-section-number">22.8</span> Which confidence interval?</a></li>
  <li><a href="#duality-of-testing-and-confidence-intervals" id="toc-duality-of-testing-and-confidence-intervals" class="nav-link" data-scroll-target="#duality-of-testing-and-confidence-intervals"><span class="header-section-number">22.9</span> Duality of testing and confidence intervals</a></li>
  <li><a href="#review" id="toc-review" class="nav-link" data-scroll-target="#review"><span class="header-section-number">22.10</span> Review</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Estimation Part 2</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>In these notes, we will continue our discussion of the problem of estimation.</p>
<section id="learning-objectives" class="level2" data-number="22.1">
<h2 data-number="22.1" class="anchored" data-anchor-id="learning-objectives"><span class="header-section-number">22.1</span> Learning objectives</h2>
<p>After this lesson, you will be able to</p>
<ul>
<li>Explain the concept of confidence intervals</li>
<li>Use Monte Carlo methods to construct a confidence interval for the parameter of a distribution.</li>
<li>Explain the central limit theorem and use it to construct a confidence interval for the parameter of a distribution</li>
<li>Explain the connection between confidence intervals and hypothesis testing</li>
</ul>
</section>
<section id="recap-estimation-so-far" class="level2" data-number="22.2">
<h2 data-number="22.2" class="anchored" data-anchor-id="recap-estimation-so-far"><span class="header-section-number">22.2</span> Recap: estimation so far</h2>
<p>Last week, we began discussing the problem of estimation, where we are interested in determining the value of some quantity out there in the world (most commonly the parameter of a distribution). We focused in our previous lectures on point estimation, where we are concerned with simply giving a single number as our “best guess” of the true value of the parameter of interest. Still, we mentioned several times in lecture the fact that our “best guess”, i.e., our estimate, would itself be random because the data is random. The result of this randomness is that for any estimate that we might produce, we have level of “uncertainty” associated to that estimate.</p>
<section id="example-gone-fishing" class="level3" data-number="22.2.1">
<h3 data-number="22.2.1" class="anchored" data-anchor-id="example-gone-fishing"><span class="header-section-number">22.2.1</span> Example: gone fishing</h3>
<p>Suppose we are working for the Department of Natural Resources (DNR), tasked with estimating how many fish live in Lake Mendota. Our colleagues in ecology go out in the field and come up with an estimate of 10,848 fish in Lake Mendota (note: this number is completely fictional; indeed, I am not even sure that it is of the correct order of magnitude).</p>
<p>Presumably, the exact number of fish in Lake Mendota changes from day to day, week to week, month to month, etc. So perhaps we would not object much if someone came along and revised this number from, say, 10,848 to 10,306. Perhaps we would not even object much if this estimate were revised by a thousand fish in one direction or the other. Still, there are a range of values around 10,848 that seem like “reasonable” guesses, and there are other values that seem pretty clearly “unreasonable”. For example, revising our estimate from approximately 10,000 fish down to 1,000 fish seems extreme.</p>
<p>What we would like, ideally, is to provide a range of values for our estimate that capture our level of uncertainty (or, conversely, our level of certainty, i.e., … confidence) about this number. Specifically, we would like to produce an interval that is somehow “usually” correct.</p>
<p>But what does it mean for an interval to be “usually right”?</p>
</section>
</section>
<section id="enter-confidence-intervals" class="level2" data-number="22.3">
<h2 data-number="22.3" class="anchored" data-anchor-id="enter-confidence-intervals"><span class="header-section-number">22.3</span> Enter: Confidence intervals</h2>
<p>Suppose we observe a particular value for our statistic <span class="math inline">\(S\)</span>. Remember, <span class="math inline">\(S = S(X_1,X_2,\dots,X_n)\)</span> is a function of our data and estimates our parameter of interest, say, <span class="math inline">\(\theta\)</span>. We’ll assume further, for simplicity, that <span class="math inline">\(\mathbb{E} S = \theta\)</span>. That is, our estimator is unbiased for <span class="math inline">\(\theta\)</span>. Note that this isn’t always the case, but further discussion of the case where <span class="math inline">\(S\)</span> is biased will have to wait (and there’s no need to make things more complicated than they already are!).</p>
<p>We would like to be able to give an interval of values around our observed value of <span class="math inline">\(S\)</span> such that <span class="math inline">\(\theta\)</span> is (with some level of certainty, anyway), in that interval.</p>
<p>That is, roughly speaking, the definition of a confidence interval. We’ll put that definition on firmer ground soon, but let’s start by building some intuition and recalling some ideas from earlier in the semester.</p>
<p>First things first: <span class="math inline">\(S = S(X_1,X_2,\dots,X_n)\)</span> is a random variable, thus it has a distribution.</p>
<ul>
<li>If we knew that distribution, we could compute <span class="math inline">\(\mathbb{E} S = \theta\)</span> exactly</li>
<li>Of course, in practice, we don’t know that distribution</li>
</ul>
<p>But let’s imagine for now that we knew the true distribution of <span class="math inline">\(S\)</span>.</p>
<p><strong>Example:</strong> for the sake of easy math, let’s say that <span class="math inline">\(S\)</span> is the sample mean of <span class="math inline">\(n=25\)</span> independent draws from <span class="math inline">\(\operatorname{Normal}(\mu=1, \sigma=1)\)</span>.</p>
<p>The true value of <span class="math inline">\(\mathbb{E} S\)</span> in this case is <span class="math display">\[
\newcommand{\E}{\mathbb{E}}
\E S = \E \frac{1}{n} \sum_{i=1}^n X_i
= \frac{1}{n} \sum_{i=1}^n \E X_i
= \frac{1}{n} \sum_{i=1}^n \mu
= \mu = 1,
\]</span></p>
<p>Where we have used the facts that</p>
<ol type="1">
<li><span class="math inline">\(S\)</span> is the sample mean, i.e., <span class="math inline">\(S = \sum_{i=1}^n X_i / n\)</span></li>
<li>The expectation operator is linear: <span class="math inline">\(\mathbb{E} aX = a \mathbb{E} X\)</span> and expectation of a sum is the sum of expectations</li>
<li><span class="math inline">\(\mathbb{E} X_i = \mu\)</span> (because <span class="math inline">\(X_i \sim \operatorname{Normal}(1,1)\)</span> for all <span class="math inline">\(i\)</span>)</li>
</ol>
<p>In fact, in this case, we know the exact distribution of <span class="math inline">\(S\)</span>.</p>
<ul>
<li><span class="math inline">\(S\)</span> is the mean of <span class="math inline">\(n=25\)</span> independent <span class="math inline">\(\operatorname{Normal}(1,1)\)</span> RVs</li>
<li><span class="math inline">\(S \sim \operatorname{Normal}(\mu=1,\sigma=1/\sqrt{n})\)</span> (you’ll prove this for yourself in a theory class in the future, for now refer to Wikipedia or any probability textbook if you want to see why this is true)</li>
<li>Plugging in <span class="math inline">\(n=25\)</span>, <span class="math inline">\(S \sim \operatorname{Normal}(\mu=1,\sigma=1/5)\)</span></li>
</ul>
<p>Let’s use R to compute the exact quantiles of this distribution.</p>
<p><strong>Reminder:</strong> We do that with the function <code>qnorm</code>. Analogously to <code>rnorm</code>, <code>pnorm</code> and <code>dnorm</code>, think “<code>q</code> for quantiles”</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The first argument to qnorm is a vector of the quantiles we want (given as probabilities).</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Asking for the 2.5% and 97.5% quantiles.</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>( <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>), <span class="at">mean=</span><span class="dv">1</span>, <span class="at">sd=</span><span class="dv">1</span><span class="sc">/</span><span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6080072 1.3919928</code></pre>
</div>
</div>
<p>What this says is that if <span class="math inline">\(Z \sim \operatorname{Normal}(\mu=1, \sigma=1/5)\)</span>, then 2.5% of the time <span class="math inline">\(Z\)</span> will be less than <span class="math inline">\(\approx 0.608\)</span>, and 97.5% of the time <span class="math inline">\(Z\)</span> will be less than <span class="math inline">\(\approx 1.392\)</span>.</p>
<p>Putting those facts together, we conclude that <span class="math display">\[
\Pr\left[ 0.608 \le S \le 1.392 \right] = 0.95.
\]</span></p>
<p>95% of the time, <span class="math inline">\(S\)</span> is between <span class="math inline">\(0.608\)</span> and <span class="math inline">\(1.392\)</span>.</p>
</section>
<section id="aside-wait-that-wasnt-a-confidence-interval" class="level2" data-number="22.4">
<h2 data-number="22.4" class="anchored" data-anchor-id="aside-wait-that-wasnt-a-confidence-interval"><span class="header-section-number">22.4</span> Aside: wait, that wasn’t a confidence interval!</h2>
<p>Now, if you’ve seen confidence intervals before, you might see a small problem with this.</p>
<p>The definition of a <span class="math inline">\((1-\alpha)\)</span>-confidence interval for the parameter <span class="math inline">\(\theta\)</span> (for simplicity, just think of <span class="math inline">\(\theta\)</span> as the mean, <span class="math inline">\(\mu\)</span>, here, or the probability <span class="math inline">\(p\)</span> from our widgets example, but it could be any quantity of interest) is</p>
<ul>
<li>a data-dependent interval <span class="math inline">\(C(X_1,X_2,\dots,X_n) = (L,U)\)</span> (<span class="math inline">\(L,U\)</span> for “lower” and “upper”; they are functions of the data!),</li>
<li>with the property that when the data are drawn under the distribution with parameter <span class="math inline">\(\theta\)</span> (note: we write <span class="math inline">\(\Pr[ \dots ; \theta]\)</span> to drive home the fact that this is the probability under the model where <span class="math inline">\(\theta\)</span> is the true parameter),</li>
</ul>
<p><span class="math display">\[
\Pr\left[ \theta \in C(X_1,X_2,\dots,X_n) ; \theta \right] = 1-\alpha.
\]</span></p>
<p>Do you see the issue? In our statements about <span class="math inline">\(S\)</span> above, all the randomness was in <span class="math inline">\(S\)</span>, and our interval <span class="math inline">\((0.608,1.392)\)</span> was not random at all. Here, on the other hand, all the randomness is in the interval <span class="math inline">\(C\)</span>.</p>
<p><strong>Why this discrepancy?</strong></p>
<p>Well, the short answer is that when classical statistics (think Z-scores, confidence intervals, t-tests, etc) was invented, we didn’t have fast, cheap computers.</p>
<p>What we are aiming to teach you in this course is what people like R. A. Fisher, Karl Pearson and W. S. Gossett (a.k.a. T. Student) would have done (I think, anyway) if they had laptops and access to cloud computing.</p>
<p>Our goal here is to compute an interval that captures our level of uncertainty about our estimate. Roughly speaking, wider intervals will correspond to higher levels of uncertainty.</p>
<p>There are many different ways to construct such intervals, each with its own interpretation.</p>
<p>There are many approaches to this problem beyond the simulation-based approach we’re taking today. If you’re impatient to read more, <a href="https://en.wikipedia.org/wiki/Interval_estimation">this Wikipedia article</a> is a good place to start. Any introductory statistics textbook will also have a good treatment of confidence intervals in particular, though I especially like John Rice’s book, <em>Mathematical Statistics and Data Analysis</em>.</p>
<p>If you are already familiar with confidence intervals, you should be able to convince yourself (after meditating on this and the next few sections) that this “simulation-based” approach and the classical confidence interval are, in a sense, two sides of the same coin.</p>
<p>Unfortunately, the details of that are beyond the scope of our course, but if you’re taking a theoretical statistics course now or in the near future, keep it in mind!</p>
</section>
<section id="capturing-uncertainty-in-our-estimate" class="level2" data-number="22.5">
<h2 data-number="22.5" class="anchored" data-anchor-id="capturing-uncertainty-in-our-estimate"><span class="header-section-number">22.5</span> Capturing uncertainty in our estimate</h2>
<p>So let’s return to our illustrative example above. Recall that</p>
<ul>
<li><span class="math inline">\(S\)</span> is the sample mean of <span class="math inline">\(n=25\)</span> independent draws from <span class="math inline">\(\operatorname{Normal}(\mu=1, \sigma=1)\)</span>.</li>
<li><span class="math inline">\(\mathbb{E} S = \mu = 1\)</span>.</li>
<li><span class="math inline">\(S \sim \operatorname{Normal}(\mu=1,\sigma=1/5)\)</span></li>
</ul>
<p>In our experiment above, we computed an exact interval, <span class="math inline">\(C = (0.6080072, 1.3919928)\)</span>, such that with probability <span class="math inline">\(0.95\)</span>, <span class="math inline">\(S \in C\)</span>.</p>
<p>How does that help us to express (un)certainty?</p>
<p>Well, the standard deviation of <span class="math inline">\(S\)</span> is <span class="math inline">\(\sigma/\sqrt{n}\)</span>. If we increase <span class="math inline">\(n\)</span>, the standard deviation of <span class="math inline">\(S\)</span> decreases, and our resulting confidence interval gets narrower.</p>
<p>For example, if <span class="math inline">\(n=100\)</span>, then <span class="math inline">\(S \sim \operatorname{Normal}(\mu=1,\sigma=1/10)\)</span>, and our quantiles become</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>( <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>), <span class="at">mean=</span><span class="dv">1</span>, <span class="at">sd=</span><span class="dv">1</span><span class="sc">/</span><span class="fu">sqrt</span>(<span class="dv">100</span>) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8040036 1.1959964</code></pre>
</div>
</div>
<p>Compare that with our interval <span class="math inline">\((0.6080072, 1.3919928)\)</span> when <span class="math inline">\(n=25\)</span>.</p>
<p>This is in keeping with the fact that as we collect more data (i.e., observe more samples), we get more confident about our predictions. Again, a narrower interval corresponds to a higher level of confidence.</p>
</section>
<section id="okay-but-we-dont-know-mathbbe-s" class="level2" data-number="22.6">
<h2 data-number="22.6" class="anchored" data-anchor-id="okay-but-we-dont-know-mathbbe-s"><span class="header-section-number">22.6</span> Okay, but we don’t know <span class="math inline">\(\mathbb{E} S\)</span></h2>
<p>We have been assuming in our example above that we know the expectation of <span class="math inline">\(S\)</span>, which is… well, never true in practice.</p>
<p>Indeed, we are assuming that we know the full distribution of <span class="math inline">\(S\)</span>, which is true even less often.</p>
<p><em>If we knew the true parameter</em> (i.e., <span class="math inline">\(\theta = \mathbb{E} S\)</span>), we could generate data from the “true” distribution like above.</p>
<p>In particular, we could see what data and/or what values of <span class="math inline">\(S\)</span> are “typical” for that value of the parameter <span class="math inline">\(\theta\)</span>.</p>
<p>This suggests a solution: let’s estimate our model (i.e., estimate the parameter <span class="math inline">\(\theta\)</span>, presumably using <span class="math inline">\(\hat{\theta} = S(X_1,X_2,\dots,X_n)\)</span> as our estimate). Then, let’s generate data from our model, pretending that <span class="math inline">\(S(X_1,X_2,\dots,X_n)\)</span> is the true parameter, and see what values of our estimator are “typical”, by computing our statistic on the generated data. Said another way, we pretend to believe that our estimated model is the truth and generate data from it many times to get a sense of the “typical” behavior of <span class="math inline">\(S\)</span>.</p>
<p>In essence, we are doing the following:</p>
<ul>
<li>Pretend for now that our estimated parameter is the truth</li>
<li>Generate data from our model with that parameter</li>
<li>Compute the statistic <span class="math inline">\(S\)</span> on that data.</li>
</ul>
<p>This gives us multiple replicates of our data under the setting where our observed value of <span class="math inline">\(S\)</span> is the truth.</p>
<p>In a sense, these samples are values of our statistic that would be “reasonable” if the true parameter were equal to <span class="math inline">\(s= S(x_1,x_2,\dots,x_n)\)</span>, where <span class="math inline">\(x_1,x_2,\dots,x_n\)</span> are our observed data.</p>
<p><strong>Aside:</strong> As we’ve mentioned before, this is a convention in statistics that upper-case letters denote random variables, while their lower-case equivalents denote the <em>observed value</em> of that random variable. So in this case, <span class="math inline">\(X_1,X_2,\dots,X_n\)</span> are the random variables observed in our sample, while <span class="math inline">\(x_1,x_2,\dots,x_n\)</span> would denote the specific values that they take on some particular draw of those variables.</p>
<p>This is a tricky distinction at first, so don’t worry if it takes some time to get used to!</p>
<section id="example-intervals-for-the-poisson-rate-parameter" class="level3" data-number="22.6.1">
<h3 data-number="22.6.1" class="anchored" data-anchor-id="example-intervals-for-the-poisson-rate-parameter"><span class="header-section-number">22.6.1</span> Example: Intervals for the Poisson rate parameter</h3>
<p>Suppose that we have data <span class="math inline">\(X_1,X_2,\dots,X_n\)</span> drawn i.i.d.~from a Poisson with unknown rate parameter <span class="math inline">\(\lambda\)</span>, and our goal is to estimate <span class="math inline">\(\lambda\)</span>.</p>
<p>Since <span class="math inline">\(\mathbb{E} X_i = \lambda\)</span> for all <span class="math inline">\(i=1,2,\dots,n\)</span>, a reasonable choice of estimator is the sample mean <span class="math inline">\(\bar{X} = n^{-1} \sum_i X_i\)</span>. Indeed, the law of large numbers guarantees that <span class="math inline">\(\bar{X}\)</span> is close to <span class="math inline">\(\lambda = \mathbb{E} X_1\)</span> with high probability.</p>
<p>Now, let’s generate data from this model, this time imagining that we don’t know the parameter <span class="math inline">\(\lambda\)</span>.</p>
<p>Instead, we’ll estimate <span class="math inline">\(\lambda\)</span> from our data, and to get a “confidence interval” for <span class="math inline">\(\lambda\)</span>, we will pretend that our estimate <span class="math inline">\(\bar{X}\)</span> is the truth and generate new copies of the data using <span class="math inline">\(\lambda = \bar{X}\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">80</span>; <span class="co"># Sample size of our data</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>lambda_true <span class="ot">&lt;-</span> <span class="fl">2.718</span>; <span class="co"># True (but unknown!) Poisson parameter</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">rpois</span>(<span class="at">n=</span>n, <span class="at">lambda=</span>lambda_true);</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(data, <span class="at">breaks=</span><span class="fu">seq</span>(<span class="sc">-</span>.<span class="dv">5</span>,<span class="fu">max</span>(data)<span class="sc">+</span>.<span class="dv">5</span>,<span class="dv">1</span>)); <span class="co"># Always good to look at your data!</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="estimation2_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Now, let’s get our estimate (just the sample mean!), pretend it’s the true value of <span class="math inline">\(\lambda\)</span>, and generate data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reminder: we say lambdahat to remind ourselves this is</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co"># an estimate of lambda.</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>lambda_hat <span class="ot">&lt;-</span> <span class="fu">mean</span>(data); <span class="co"># Sample mean is our estimate of lambda.</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate data under the distribution where lambda_hat is the rate parameter.</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="co"># To reiterate, we're pretending that our estimate is the truth and seeing what our data would look like.</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>fake_data <span class="ot">&lt;-</span> <span class="fu">rpois</span>(<span class="at">n=</span>n, <span class="at">lambda=</span>lambda_hat);</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(fake_data, <span class="at">breaks=</span><span class="fu">seq</span>(<span class="sc">-</span>.<span class="dv">5</span>,<span class="fu">max</span>(fake_data)<span class="sc">+</span>.<span class="dv">5</span>,<span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="estimation2_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In our previous example, we worked out exactly what the distribution of our statistic was, because the math was easy.</p>
<p>The math is a bit less easy now. We could, if we wanted to, work out the exact sampling distribution of the sample mean under the Poisson.</p>
<p>Instead of doing all that annoying math, though, let’s just use the computer.</p>
<p>Again, here’s the recipe:</p>
<ul>
<li>Estimate our distribution’s parameter from the data (we’ve done that with our sample mean <code>lambda_hat</code>)</li>
<li>Generate data from the distribution with parameter equal to our estimate (we just did that above)</li>
<li>Repeat the previous step many times, computing a new estimate on each new data sample. Each repetition gives us a replicate of our statistic, under the distribution where <span class="math inline">\(\lambda = \texttt{lambda_hat}\)</span>.</li>
<li>We can use that to construct a confidence interval for <span class="math inline">\(\lambda\)</span>, by looking at the quantiles of our sample.</li>
</ul>
<p>Let’s implement that:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reminder: sample size and true parameter</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>n<span class="ot">&lt;-</span> <span class="dv">80</span>; lambda_true <span class="ot">&lt;-</span> <span class="fl">2.718</span>;</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate data from the true distribution</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">rpois</span>( <span class="at">n=</span>n, <span class="at">lambda=</span>lambda_true);</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>lambda_hat <span class="ot">&lt;-</span> <span class="fu">mean</span>(data); <span class="co"># Just estimating this again to remind you</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>Nrep <span class="ot">&lt;-</span> <span class="dv">2000</span>; <span class="co"># Number of repetitions (i.e., replicates)</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>replicates <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>,Nrep); <span class="co"># We will store replicates of lambdahat here.</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ( i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>Nrep) {</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  fake_data <span class="ot">&lt;-</span> <span class="fu">rpois</span>(<span class="at">n=</span>n, <span class="at">lambda=</span>lambda_hat);</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>  replicates[i] <span class="ot">&lt;-</span> <span class="fu">mean</span>( fake_data );</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Now construct the confidence interval</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>CI <span class="ot">&lt;-</span> <span class="fu">quantile</span>( replicates, <span class="at">probs=</span><span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>) );</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(CI)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>2.525 3.2625</code></pre>
</div>
</div>
<p>Most of the time, when we run the code above, we should find that <span class="math inline">\(\lambda=2.718\)</span> is inside of that interval.</p>
<p>Sometimes, though, due to randomness in our data, the interval will not contain the true value of <span class="math inline">\(\lambda\)</span>.</p>
<p>Now, how often does that happen? Well, let’s try creating lots of intervals like the one above and count how often our interval contains the true value of <span class="math inline">\(\lambda\)</span>.</p>
<p>First, we’ll implement a function to run one instance of the experiment we just ran above.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>run_trial <span class="ot">&lt;-</span> <span class="cf">function</span>(lambdatrue, n, Nrep) {</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Run one instance of our experiment above, wherein we</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 1) Generate data from Pois(lambda_true)</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 2) Estimate lambdahat from that data.</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 3) Repeatedly generate data from Pois(lambdahat)</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 4) Use those repetitions to get an interval.</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># lambdatrue : the true lambda parameter for Poisson</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># n : sample size for the data</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Nrep : repetitions to use when computing the interval</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  data <span class="ot">&lt;-</span> <span class="fu">rpois</span>(<span class="at">n=</span>n, <span class="at">lambda=</span>lambdatrue);</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>  lambdahat <span class="ot">&lt;-</span> <span class="fu">mean</span>(data);</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>  replicates <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>,Nrep); <span class="co"># We will store replicates of lambdahat here.</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> ( i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>Nrep) {</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>    fake_data <span class="ot">&lt;-</span> <span class="fu">rpois</span>(<span class="at">n=</span>n, <span class="at">lambda=</span>lambdahat);</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>    replicates[i] <span class="ot">&lt;-</span> <span class="fu">mean</span>( fake_data );</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Now construct the confidence interval</span></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>  <span class="co"># the names=FALSE tells R to return the quantiles with no header</span></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>  CI <span class="ot">&lt;-</span> <span class="fu">quantile</span>( replicates, <span class="at">probs=</span><span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>), <span class="at">names=</span><span class="cn">FALSE</span> );</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>( (CI[<span class="dv">1</span>] <span class="sc">&lt;</span> lambdatrue) <span class="sc">&amp;</span> (lambdatrue <span class="sc">&lt;</span> CI[<span class="dv">2</span>]) );</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, let’s try repeating the experiment many times by calling <code>run_trial(lambdatrue=2.718, n=80, Nrep=1000 )</code> a bunch.</p>
<p><strong>Important note:</strong> This section of code might take a minute or two to run. Each time we call <code>run_trial</code>, we are generating <code>n</code> Poisson variables <code>Nrep</code> times. And here we are about to call <code>run_trial</code> many times (the variable is <code>Nexpt</code> below). So, in total, we’re generating <code>n*Nrep*Nexpt</code> random variables, and random variables aren’t cheap (think back to our discussion of randomness in our Monte Carlo lectures)!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># </span><span class="al">NOTE</span><span class="co">: This section of code might take a minute or two to run!</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>Nexpt <span class="ot">&lt;-</span> <span class="dv">500</span>; <span class="co"># Number of times to run the experiment</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>expt_results <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>,Nexpt); <span class="co"># Vector to store results</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>Nexpt) {</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  expt_results[i] <span class="ot">&lt;-</span> <span class="fu">run_trial</span>(<span class="at">lambdatrue=</span><span class="fl">2.718</span>, <span class="at">n=</span><span class="dv">80</span>, <span class="at">Nrep=</span><span class="dv">1000</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Count what fraction of the time we were correct.</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(expt_results)<span class="sc">/</span><span class="fu">length</span>(expt_results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.954</code></pre>
</div>
</div>
<p>The result <em>should</em> be about .95.</p>
<p>This is not a coincidence– remember we chose the quantiles (0.025, 0.975) to mimic a 95% confidence interval. Our experiment shows that the intervals that we constructed above based on simulations are (approximately) 95% confidence intervals!</p>
<p>Let’s do another worked example, revisiting the exponential distribution.</p>
</section>
<section id="example-estimating-the-rate-in-the-exponential-distribution" class="level3" data-number="22.6.2">
<h3 data-number="22.6.2" class="anchored" data-anchor-id="example-estimating-the-rate-in-the-exponential-distribution"><span class="header-section-number">22.6.2</span> Example: estimating the rate in the exponential distribution</h3>
<p>Suppose that we observe data <span class="math inline">\(X_1,X_2,\dots,X_n\)</span> i.i.d. from an exponential distribution with rate parameter <span class="math inline">\(\lambda\)</span>, so that <span class="math inline">\(\mathbb{E} X_1 = 1/\lambda\)</span>, and our goal is to estimate <span class="math inline">\(\lambda\)</span>.</p>
<p>The plug-in principal and/or the method of moments suggests that we use <span class="math inline">\(1/\bar{X}\)</span> as our estimate of <span class="math inline">\(\lambda\)</span>.</p>
<p>Applying our simulation-based CI recipe, we should:</p>
<ol type="1">
<li>Estimate <span class="math inline">\(\lambda\)</span> as <span class="math inline">\(\hat{\lambda} = 1/\bar{X}\)</span>.</li>
<li>Repeatedly generate data as though <span class="math inline">\(\hat{\lambda}\)</span> were the true value of the parameter, and “re-estimate” <span class="math inline">\(\lambda\)</span> on each such data set.</li>
<li>Use the histogram of the resulting “fake” estimates to estimate our interval.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>true_rate <span class="ot">&lt;-</span> <span class="dv">5</span>;</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>nsamp <span class="ot">&lt;-</span> <span class="dv">25</span>; <span class="co">#sample size in the data that we generate.</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>obsd_data <span class="ot">&lt;-</span> <span class="fu">rexp</span>(<span class="at">n=</span>nsamp, <span class="at">rate=</span>true_rate);</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate the rate parameter lambda from the data.</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Recall that the mean is 1/rate, so we can estimate the</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="co"># rate by taking the sample mean Xbar, which estimates 1/rate,</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="co"># and then using 1/Xbar as our estimate of the rate lambda.</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>estd_rate <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">/</span><span class="fu">mean</span>(obsd_data);</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>NMC <span class="ot">&lt;-</span> <span class="dv">2000</span>;</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>replicates <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, NMC);</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ( i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>NMC) {</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>  fake_data <span class="ot">&lt;-</span> <span class="fu">rexp</span>(nsamp, <span class="at">rate=</span>estd_rate);</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>  <span class="co"># We want to estimate the sampling distribution of the estimated</span></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># rate parameter from the data.</span></span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>  replicates[i] <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">/</span><span class="fu">mean</span>(fake_data);</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Now construct the confidence interval</span></span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a><span class="co"># the names=FALSE tells R to return the quantiles with no header</span></span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>CI <span class="ot">&lt;-</span> <span class="fu">quantile</span>( replicates, <span class="at">probs=</span><span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>), <span class="at">names=</span><span class="cn">FALSE</span> );</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>CI</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.997693 6.662774</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>(CI[<span class="dv">1</span>] <span class="sc">&lt;</span> true_rate) <span class="sc">&amp;</span> (true_rate <span class="sc">&lt;</span> CI[<span class="dv">2</span>]) ;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<p>Okay, let’s package that up in a function and run it a bunch of times to check whether or not our CI is achieve its stated rate of <span class="math inline">\(0.95\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>run_exprate_expt <span class="ot">&lt;-</span> <span class="cf">function</span>( nsamp, true_rate ) {</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  obsd_data <span class="ot">&lt;-</span> <span class="fu">rexp</span>(<span class="at">n=</span>nsamp, <span class="at">rate=</span>true_rate);</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Estimate the rate parameter lambda from the data.</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Recall that the mean is 1/rate, so we can estimate the</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># rate by taking the sample mean Xbar, which estimates 1/rate,</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># and then using 1/Xbar as our estimate of the rate lambda.</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  estd_rate <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">/</span><span class="fu">mean</span>(obsd_data);</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Now generate "fake" data sets and estimate lambda on each.</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>  NMC <span class="ot">&lt;-</span> <span class="dv">2000</span>;</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>  replicates <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, NMC);</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> ( i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>NMC) {</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>    fake_data <span class="ot">&lt;-</span> <span class="fu">rexp</span>(nsamp, <span class="at">rate=</span>estd_rate);</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>    <span class="co"># We want to estimate the sampling distribution of the estimated</span></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># rate parameter from the data.</span></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>    replicates[i] <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">/</span><span class="fu">mean</span>(fake_data);</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Now construct the confidence interval</span></span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>  <span class="co"># the names=FALSE tells R to return the quantiles with no header</span></span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>  CI <span class="ot">&lt;-</span> <span class="fu">quantile</span>( replicates, <span class="at">probs=</span><span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>), <span class="at">names=</span><span class="cn">FALSE</span> );</span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>( (CI[<span class="dv">1</span>] <span class="sc">&lt;</span> true_rate) <span class="sc">&amp;</span> (true_rate <span class="sc">&lt;</span> CI[<span class="dv">2</span>]) );</span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Now let's run the above experiment a few thousand times</span></span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a><span class="co"># and see how often we "catch" the true value of lambda.</span></span>
<span id="cb16-27"><a href="#cb16-27" aria-hidden="true" tabindex="-1"></a>lambda_true <span class="ot">&lt;-</span> <span class="dv">2</span>;</span>
<span id="cb16-28"><a href="#cb16-28" aria-hidden="true" tabindex="-1"></a>nsamp <span class="ot">&lt;-</span> <span class="dv">100</span>;</span>
<span id="cb16-29"><a href="#cb16-29" aria-hidden="true" tabindex="-1"></a>M <span class="ot">&lt;-</span> <span class="dv">2000</span>;</span>
<span id="cb16-30"><a href="#cb16-30" aria-hidden="true" tabindex="-1"></a>reps <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, M);</span>
<span id="cb16-31"><a href="#cb16-31" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>M) {</span>
<span id="cb16-32"><a href="#cb16-32" aria-hidden="true" tabindex="-1"></a>  reps[i] <span class="ot">&lt;-</span> <span class="fu">run_exprate_expt</span>( nsamp, lambda_true )</span>
<span id="cb16-33"><a href="#cb16-33" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb16-34"><a href="#cb16-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-35"><a href="#cb16-35" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(reps)<span class="sc">/</span>M</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.946</code></pre>
</div>
</div>
<p>One important thing to bear in mind is that while the simulation-based recipe demonstrated above is a fairly general approach, it only produces an <em>approximately correct</em> confidence interval, which relies on how well we can estimate the model parameter to begin with.</p>
<p><strong>Exercise:</strong> try playing around with <code>nsamp</code> and <code>lambda_true</code> in the code above. Consider what happens if <code>nsamp</code> is small (e.g., 20 or 25): <span class="math inline">\(\bar{X}\)</span> will not necessarily be close to <span class="math inline">\(\mathbb{E} \bar{X} = 1/\lambda\)</span>, and thus our estimate of <span class="math inline">\(\lambda\)</span>, <span class="math inline">\(1/\bar{X}\)</span> will likely be far from <span class="math inline">\(\lambda\)</span>, and thus our “fake” data will not actually look very much like it should. In another direction, try playing around with the parameter <span class="math inline">\(\lambda &gt; 0\)</span>. What happens if you make <span class="math inline">\(\lambda\)</span> really big or really close to zero?</p>
<p>In your discussion section and homework, you’ll get more practice with this framework. The important takeaway is this: our goal in producing lots of replicates is to get a sense of what “reasonable” other values of our statistic might have been.</p>
</section>
</section>
<section id="confidence-intervals-another-way-the-clt" class="level2" data-number="22.7">
<h2 data-number="22.7" class="anchored" data-anchor-id="confidence-intervals-another-way-the-clt"><span class="header-section-number">22.7</span> Confidence intervals another way: the CLT</h2>
<p>Now, how do we relate the above framework to the version of confidence intervals that you might have learned in your intro courses (if you saw CIs previously; if you didn’t, no worries)?</p>
<p>The <a href="https://en.wikipedia.org/wiki/Central_limit_theorem">central limit theorem</a> states that if <span class="math inline">\(X_1,X_2,\dots\)</span> are iid random variables with shared mean <span class="math inline">\(\mu = \mathbb{E} X_1\)</span> and variance <span class="math inline">\(\sigma^2 = \operatorname{Var} X_1\)</span>, then as <span class="math inline">\(n \rightarrow \infty\)</span>, the recentered, rescaled random variable <span class="math display">\[
\frac{ \frac{1}{n} \sum_{i=1}^n X_i - \mu }{ \sqrt{ \sigma^2 / n } }
\]</span> is well approximated by a standard normal.</p>
<p>In your discussion section and your homework, you’ll run some experiments to explore this phenomenon further.</p>
<p>Specifically, what we mean by “well approximated” is that, letting <span class="math inline">\(Z \sim \operatorname{Normal}(0,1)\)</span>, for all <span class="math inline">\(t \in \mathbb{R}\)</span>,</p>
<p><span class="math display">\[
\lim_{n \rightarrow \infty} \Pr\left[ \frac{ \frac{1}{n} \sum_{i=1}^n X_i - \mu }{ \sqrt{\sigma^2/n} } \le t \right]
= \Pr[ Z \le t ].
\]</span></p>
<p><strong>Aside:</strong> if you’ve seen <em>convergence in distribution</em> before, this should look familiar– this says that the sample mean (after centering and scaling) converges in distribution to a standard normal. If you haven’t seen convergence in distribution before, not to worry. It’s just the technical name for the limit property in the equation above, and it won’t be on an exam this semester.</p>
<p>Said another way, the central limit theorem says that for large sample size, the distribution of the sample mean <span class="math inline">\(\bar{X}\)</span> is well approximated by a normal random variable with mean <span class="math inline">\(\mu = \mathbb{E} X_1\)</span> and variance <span class="math inline">\(\sigma^2/n = n^{-1} \operatorname{Var} X_1\)</span>.</p>
<section id="the-clt-in-action" class="level3" data-number="22.7.1">
<h3 data-number="22.7.1" class="anchored" data-anchor-id="the-clt-in-action"><span class="header-section-number">22.7.1</span> The CLT in action</h3>
<p>Let’s quickly do an experiment that you’ve probably seen before: watching the CLT in action.</p>
<p>Again, the CLT says that if we take a sample of i.i.d. random variables, take their mean, center it about their expectation, and rescale them by their standard deviation, they should be <em>approximately</em> normal.</p>
<p>Let’s have a look.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>NMC <span class="ot">&lt;-</span> <span class="fl">1e3</span>;</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Code to draw n iid RVs from exp(1) and compute their sample mean.</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>generate_sample_mean <span class="ot">&lt;-</span> <span class="cf">function</span>( n ) {</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  X <span class="ot">&lt;-</span> <span class="fu">rexp</span>(<span class="at">n=</span>n, <span class="at">rate=</span><span class="dv">1</span>);</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># X has mean 1, variance 1</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># See https://en.wikipedia.org/wiki/Exponential_distribution</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>( <span class="fu">mean</span>(X) )</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate a bunch of such sample means, each on n=10 data points</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>Xbar_sample_means <span class="ot">&lt;-</span> <span class="fu">rep</span>( <span class="cn">NA</span>, NMC);</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>( i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>NMC ) {</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>  Xbar_sample_means[i] <span class="ot">&lt;-</span> <span class="fu">generate_sample_mean</span>(<span class="dv">10</span>);</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a><span class="co"># We center about the mean 1,</span></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a><span class="co"># and rescale by the standard deviation of the sample mean,</span></span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a><span class="co"># sqrt( ( Var X_1 )/10 ) = sqrt(1/10)</span></span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>( (Xbar_sample_means<span class="dv">-1</span>)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">10</span>) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="estimation2_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Now let's try again, but with a larger sample size.</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Changing n=10 to n=15.</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>Xbar_sample_means <span class="ot">&lt;-</span> <span class="fu">rep</span>( <span class="cn">NA</span>, NMC);</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>( i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>NMC ) {</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  Xbar_sample_means[i] <span class="ot">&lt;-</span> <span class="fu">generate_sample_mean</span>(<span class="dv">15</span>);</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>( (Xbar_sample_means<span class="dv">-1</span>)<span class="sc">/</span>(<span class="dv">1</span><span class="sc">/</span><span class="fu">sqrt</span>(<span class="dv">15</span>)) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="estimation2_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Let’s try one more, this time with <span class="math inline">\(n=20\)</span> data points.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>Xbar_sample_means <span class="ot">&lt;-</span> <span class="fu">rep</span>( <span class="cn">NA</span>, NMC);</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>( i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>NMC ) {</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  Xbar_sample_means[i] <span class="ot">&lt;-</span> <span class="fu">generate_sample_mean</span>(<span class="dv">20</span>);</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>( (Xbar_sample_means<span class="dv">-1</span>)<span class="sc">/</span>(<span class="dv">1</span><span class="sc">/</span><span class="fu">sqrt</span>(<span class="dv">20</span>)) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="estimation2_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Now let’s crank it all the way up to <span class="math inline">\(n=30\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>Xbar_sample_means <span class="ot">&lt;-</span> <span class="fu">rep</span>( <span class="cn">NA</span>, NMC);</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>( i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>NMC ) {</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  Xbar_sample_means[i] <span class="ot">&lt;-</span> <span class="fu">generate_sample_mean</span>(<span class="dv">30</span>);</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>( (Xbar_sample_means<span class="dv">-1</span>)<span class="sc">/</span>(<span class="dv">1</span><span class="sc">/</span><span class="fu">sqrt</span>(<span class="dv">30</span>)) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="estimation2_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>With just <span class="math inline">\(20\)</span> to <span class="math inline">\(30\)</span> samples, the CLT is really kicking in– that last histogram looks pretty undeniably normal to me!</p>
<p>Just to reiterate, the underlying data here look nothing like normals:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">rexp</span>(<span class="at">n=</span><span class="dv">40</span>, <span class="at">rate=</span><span class="dv">1</span>);</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="co"># X has mean 1, variance 1</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="co"># See https://en.wikipedia.org/wiki/Exponential_distribution</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>( X<span class="dv">-1</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="estimation2_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Now, the variance of our data above is <span class="math inline">\(1\)</span>, so there is no need to worry about the rescaling part of the CLT. Let’s look at a different example where the variance is not <span class="math inline">\(1\)</span> to see what that means.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>NMC <span class="ot">&lt;-</span> <span class="fl">1e3</span>;</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>generate_sample_mean <span class="ot">&lt;-</span> <span class="cf">function</span>( n ) {</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  X <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n=</span><span class="dv">10</span>, <span class="at">mean=</span><span class="dv">1</span>, <span class="at">sd=</span><span class="dv">2</span>);</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>( <span class="fu">mean</span>(X) )</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>Xbar_sample_means <span class="ot">&lt;-</span> <span class="fu">rep</span>( <span class="cn">NA</span>, NMC);</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>( i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>NMC ) {</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>  Xbar_sample_means[i] <span class="ot">&lt;-</span> <span class="fu">generate_sample_mean</span>(n);</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>( Xbar_sample_means<span class="dv">-1</span> );</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="estimation2_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Exercise:</strong> repeat the above experiment with a different data distribution and see how large <span class="math inline">\(n\)</span> has to be for the CLT to look like a reasonably good distribution. If you play around enough with different distributions and different choices of parameter values, you should be able to find two different data distributions that have decidedly different behavior in terms of when the centered, rescaled sample mean starts to “look” normal.</p>
</section>
<section id="using-the-clt-to-build-a-ci" class="level3" data-number="22.7.2">
<h3 data-number="22.7.2" class="anchored" data-anchor-id="using-the-clt-to-build-a-ci"><span class="header-section-number">22.7.2</span> Using the CLT to build a CI</h3>
<p>So the CLT says that the (recentered, rescaled) sample mean “looks like” a standard normal once <span class="math inline">\(n\)</span> is large enough.</p>
<p><strong>Note:</strong> like the LLN, the CLT <em>doesn’t</em> tell us how large is “large enough”, but let’s assume we’re good and press on.</p>
<p>Well, looking like the standard normal is good– we know how to compute quantiles for the standard normal (cue flashback to Z-scores from your intro class…)!</p>
<p>And that means we can compute (approximate) quantiles for the (recentered, rescaled) sample mean, <span class="math display">\[
\frac{ \bar{X} - \mu }{ \sqrt{ \sigma^2 / n } },
\]</span></p>
<p>The basic idea is that we know our quantiles for the standard normal.</p>
<p>For example, if <span class="math inline">\(Z \sim \operatorname{Normal}(0,1)\)</span>, then <span class="math display">\[
0.95 = \Pr[ -1.96 \le Z \le 1.96 ]
\approx \Pr\left[ -1.96 \le \frac{ \bar{X} - \mu }{ \sqrt{ \sigma^2 / n } } \le 1.96 \right].
\]</span></p>
<p>Rearranging terms inside that second probability, <span class="math display">\[
0.95
\approx \Pr\left[ \bar{X} - 1.96 \sqrt{\sigma^2/n} \le \mu \le \bar{X} + 1.96 \sqrt{\sigma^2/n} \right]
\]</span> so <span class="math inline">\(\bar{X} \pm 1.96 \sqrt{ \sigma^2/n}\)</span> would be an (approximate) 95% CI for <span class="math inline">\(\mu\)</span> if only we knew <span class="math inline">\(\sigma^2\)</span>.</p>
<p>That’s a pesky issue that we will ignore here, but you’ll get to play around with estimating <span class="math inline">\(\sigma^2\)</span> in your homework (see below for an example of the case where we estimate the variance).</p>
<p>This confidence interval is only approximate, because it relies on the CLT, in much the same way as our simulation-based procedure above was only approximate.</p>
</section>
<section id="example-confidence-interval-for-the-mean-using-clt" class="level3" data-number="22.7.3">
<h3 data-number="22.7.3" class="anchored" data-anchor-id="example-confidence-interval-for-the-mean-using-clt"><span class="header-section-number">22.7.3</span> Example: confidence interval for the mean using CLT</h3>
<p>Let’s consider the problem of estimating the mean of a <a href="https://en.wikipedia.org/wiki/Geometric_distribution">geometric random variable</a>. For a geometric random variable with parameter <span class="math inline">\(p\)</span>, the mean is <span class="math inline">\((1-p)/p\)</span> (see <code>?rgeom</code>).</p>
<p>Suppose that we observe data <span class="math inline">\(X_1,X_2,\dots,X_n\)</span> drawn i.i.d. according to a geometric distribution with parameter <span class="math inline">\(p\)</span>. To obtain a confidence interval for the mean, we begin by noting that the expectation of a geometric random variable <span class="math display">\[
\mathbb{E} \bar{X} = \frac{1-p}{p},
\]</span></p>
<p>and the variance is <span class="math inline">\((1-p)/(n p^2)\)</span> (the variance of a single geometric RV is <span class="math inline">\((1-p)/p^2\)</span>, so the variance of a mean of <span class="math inline">\(n\)</span> of them is this quantity divided by <span class="math inline">\(n\)</span>). You can check both of these facts on the Wikipedia page linked above. Bear in mind that in R, the geometric RV counts the number of flips <em>before</em> the first heads, so it can take the value <span class="math inline">\(0\)</span>.</p>
<p>The central limit theorem says that the quantity <span class="math display">\[
\frac{ \bar{X} - (1-p)/p }{ \sqrt{(1-p)/n}/p }
\]</span></p>
<p>should be (approximately) normal with mean zero and variance one.</p>
<p>Let’s first check that this is the case.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>ptrue <span class="ot">&lt;-</span> <span class="fl">0.1</span>;</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>nsamp <span class="ot">&lt;-</span> <span class="dv">30</span>;</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>M <span class="ot">&lt;-</span> <span class="dv">2000</span>;</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>replicates <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, M);</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>( i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>M) {</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  data <span class="ot">&lt;-</span> <span class="fu">rgeom</span>(<span class="at">n=</span>nsamp, <span class="at">prob=</span>ptrue);</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  replicates[i] <span class="ot">&lt;-</span> <span class="fu">mean</span>( data ); <span class="co"># = Xbar.</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>true_mean <span class="ot">&lt;-</span> (<span class="dv">1</span><span class="sc">-</span>ptrue)<span class="sc">/</span>ptrue;</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>true_var <span class="ot">&lt;-</span> (<span class="dv">1</span><span class="sc">-</span>ptrue)<span class="sc">/</span>ptrue<span class="sc">^</span><span class="dv">2</span>;</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>( (replicates<span class="sc">-</span>true_mean)<span class="sc">/</span><span class="fu">sqrt</span>(true_var<span class="sc">/</span>nsamp) );</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="estimation2_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The approximation isn’t perfect– the fact that geometric RVs are non-negative means that the sampling distribution of the sample mean is skewed to the right. Further, the geometric distribution is discrete, which complicates things further. Still, let’s press on and see if this is a good enough approximation.</p>
<p><strong>Note:</strong> you may want to look at what happens if you decrease the number of samples (e.g., down to 25) or increase them (e.g., up to 35 or 40).</p>
<p>Now, let’s use this fact to construct a CLT-based confidence interval for the mean <span class="math inline">\(1/p\)</span> under the geometric distribution.</p>
<p>Suppose that we observe the following data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">6</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">11</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">0</span> );</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Our sample mean is</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>xbar <span class="ot">&lt;-</span> <span class="fu">mean</span>(data);</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>xbar</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.333333</code></pre>
</div>
</div>
<p>Now, to construct our confidence interval for the mean <span class="math inline">\((1-p)/p\)</span>, we need to have an estimate for the variance. Remember, <span class="math display">\[
\frac{ \bar{X} - (1-p)/p }{ \sqrt{(1-p)/n}/p }
\]</span> will be approximately normal.</p>
<p>One option for estimating the variance would be to estimate <span class="math inline">\(p\)</span> and then plug that into the expression for the variance. <strong>Exercise:</strong> try that!</p>
<p>Here, though, let’s estimate the variance the easy way– computing the sample variance of the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>varhat <span class="ot">&lt;-</span> <span class="fu">var</span>( data );</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>varhat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.988506</code></pre>
</div>
</div>
<p>Plugging this into the CLT, a <span class="math inline">\(0.95\)</span> confidence interval is</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>( data )</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>( xbar <span class="sc">-</span> <span class="fl">1.96</span><span class="sc">*</span><span class="fu">sqrt</span>( varhat<span class="sc">/</span>n ), xbar <span class="sc">+</span> <span class="fl">1.96</span><span class="sc">*</span><span class="fu">sqrt</span>( varhat<span class="sc">/</span>n ))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5340869 2.1325797</code></pre>
</div>
</div>
<p>The true parameter was <span class="math inline">\(p = 0.33\)</span>, so the true mean is</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>truep <span class="ot">&lt;-</span> <span class="fl">0.33</span>;</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>truemean <span class="ot">&lt;-</span> (<span class="dv">1</span><span class="sc">-</span>truep)<span class="sc">/</span>truep</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>truemean</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.030303</code></pre>
</div>
</div>
<p>Our CI caught the mean! Great!</p>
<p><strong>Exercise:</strong> repeat our experiment from earlier to estimate how often the above CLT-based confidence interval contains the true mean. You’ll want to repeatedly</p>
<ol type="1">
<li>Generate <span class="math inline">\(n=30\)</span> random geometric RVs with success probability <span class="math inline">\(p=0.33\)</span>.</li>
<li>Compute the sample mean and sample variance.</li>
<li>Use these to build the confidence interval</li>
<li>Check whether or not the CI contains the true mean <span class="math inline">\((1-p)/p = 2.03030\)</span>.</li>
</ol>
<p>Repeat the above a couple of thousand times and check how often the CI contains the true mean. It <em>should</em> be about <span class="math inline">\(0.95\)</span>, though of course it won’t be exact, both because of randomness and because the CLT is only an approximation.</p>
</section>
</section>
<section id="which-confidence-interval" class="level2" data-number="22.8">
<h2 data-number="22.8" class="anchored" data-anchor-id="which-confidence-interval"><span class="header-section-number">22.8</span> Which confidence interval?</h2>
<p>Now you know two completely different ways to construct confidence intervals! Unfortunately, which one is the “right one” is a tricky question.</p>
<p>Sometimes it’s a question of which one is easier (i.e., requires less computer time and/or thinking time).</p>
<p>Sometimes there are obvious reasons why one or the other will be more accurate than the other (e.g., because you know that the CLT is a good approximation even for small <span class="math inline">\(n\)</span> for the data distribution).</p>
</section>
<section id="duality-of-testing-and-confidence-intervals" class="level2" data-number="22.9">
<h2 data-number="22.9" class="anchored" data-anchor-id="duality-of-testing-and-confidence-intervals"><span class="header-section-number">22.9</span> Duality of testing and confidence intervals</h2>
<p>One important observation that we should make (but not one that you need to know for an exam!), is that there is a connection between confidence intervals, which we have been discussing, and the problem of testing that we discussed in previous lectures.</p>
<p>Let’s recall that the idea behind a confidence interval is that it is a random interval, and a confidence interval with confidence level <span class="math inline">\(1-\alpha\)</span> should contain our parameter of interest with probability <span class="math inline">\(1-\alpha\)</span>.</p>
<p>Let’s call our random interval <span class="math inline">\(C = (L,U)\)</span>, bearing in mind that <span class="math inline">\(C\)</span> is a random interval, which depends on our observed data. In particular, letting <span class="math inline">\(\theta\)</span> denote the true value of our parameter of interest, our confidence interval <span class="math inline">\(C\)</span> obeys the property that <span class="math display">\[
\Pr[ \theta \in C ] = \Pr[ L \le \theta \le U ] = 1 - \alpha.
\]</span></p>
<p>Suppose that we wish to test the hypothesis <span class="math display">\[
H_0 : \theta = \theta_0,
\]</span></p>
<p>where <span class="math inline">\(\theta_0\)</span> is some particular value. For example, perhaps the parameter <span class="math inline">\(\theta\)</span> describes the size of the difference between two groups, and <span class="math inline">\(\theta_0\)</span> corresponds to that difference being zero.</p>
<p>Consider the following test of <span class="math inline">\(H_0\)</span>: given our data, compute the confidence interval <span class="math inline">\(C\)</span>. If <span class="math inline">\(\theta_0 \in C\)</span>, accept <span class="math inline">\(H_0\)</span>. If <span class="math inline">\(\theta_0 \not \in C\)</span>, reject <span class="math inline">\(H_0\)</span>.</p>
<p>It turns out that if <span class="math inline">\(C\)</span> is a <span class="math inline">\(100(1-\alpha)\)</span> confidence interval, then this test has level <span class="math inline">\(\alpha\)</span>. Let’s see why this is.</p>
<p>By the definition of our test, <span class="math display">\[
\Pr[ \text{ reject } ; H_0 ]
=
\Pr[ \theta_0 \not \in C; H_0 ]
=
1-\Pr[ \theta_0 \in C; H_0 ].
\]</span></p>
<p>Now, because <span class="math inline">\(C\)</span> is a <span class="math inline">\(100(1-\alpha)\)</span>-level confidence interval, <span class="math inline">\(\Pr[ \theta_0 \in C; H_0 ] = 1-\alpha\)</span>. Therefore, <span class="math display">\[
\Pr[ \text{ reject } ; H_0 ] = \alpha.
\]</span></p>
<p>That is, our test has level <span class="math inline">\(\alpha\)</span>.</p>
<p>It turns out that this argument runs the other way, too: given any test with level <span class="math inline">\(\alpha\)</span>, we can construct a <span class="math inline">\(100(1-\alpha)\)</span> confidence interval.</p>
<p><strong>Challenge:</strong> sketch how we might do this. Imagine that we have a procedure such that for any value of <span class="math inline">\(\theta_0\)</span>, we can conduct a level-<span class="math inline">\(\alpha\)</span> test of the hypothesis <span class="math display">\[
H_0 : \theta = \theta_0.
\]</span> Explain how to turn this into a <span class="math inline">\(100(1-\alpha)\)</span> confidence interval for <span class="math inline">\(\theta\)</span>.</p>
</section>
<section id="review" class="level2" data-number="22.10">
<h2 data-number="22.10" class="anchored" data-anchor-id="review"><span class="header-section-number">22.10</span> Review</h2>
<ul>
<li>Uncertainty in point estimates</li>
<li>Probability intervals for estimator values</li>
<li>MC Confidence interval for parameter value</li>
<li>The Central Limit Theorem</li>
<li>Parametric Confidence intervals (CLT)</li>
<li>Comparison of MC vs CLT estimation assumptions</li>
<li>Duality of testing &amp; estimation</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
  </div>
  <div class="nav-page nav-page-next">
      <a href="./estimation2_practice.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Interval Estimation Practice</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>