<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Brian Powers">
<meta name="dcterms.date" content="2025-03-31">

<title>STAT 340: Data Science II - 29&nbsp; R10 multiple regression further concepts</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./mlr_practice.html" rel="next">
<link href="./prediction2.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./prediction1.html">Prediction</a></li><li class="breadcrumb-item"><a href="./R09_Multiple_Regression.html"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">R10 multiple regression further concepts</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">STAT 340: Data Science II</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">STAT 340 Index</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false">
 <span class="menu-text">Sampling</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_rv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Probability and Random Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R01_Prob_RVs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Probability and Random Variable R Examples</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rv_practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Probability and Random Variables Practice</span></span></a>
  </div>
</li>
          <li class="px-0"><hr class="sidebar-divider hi "></li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Random Variable Distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R02_Distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Random Variable Distributions R Examples</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cov_practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Independence and Conditional Probability Practice</span></span></a>
  </div>
</li>
          <li class="px-0"><hr class="sidebar-divider hi "></li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Monte Carlo</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R03_MonteCarloExamples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Monte Carlo Examples</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mc_practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Monte Carlo Practice</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R_MonteCarlo_Battleship.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Monte Carlo Battleship</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false">
 <span class="menu-text">Testing</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./testing1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Introduction to Statistical Testing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R04_Monte_Carlo_Testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Monte Carlo Testing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./testing1_practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Monte Carlo Testing Practice</span></span></a>
  </div>
</li>
          <li class="px-0"><hr class="sidebar-divider hi "></li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./testing2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Statistical Testing, Continued</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R05_testing_Additional_Examples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Monte Carlo Testing: Additional Examples</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./testing2_practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Testing and Power Practice</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false">
 <span class="menu-text">Estimation</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./estimation1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Estimation Part 1</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./estimation1_practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Point Estimation Practice</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R06_More_Estimation_Examples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Estimation Examples</span></span></a>
  </div>
</li>
          <li class="px-0"><hr class="sidebar-divider hi "></li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./estimation2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Estimation Part 2</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./estimation2_practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Interval Estimation Practice</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R07_More_Estimation_and_CI_Examples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Interval Estimation Examples</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Prediction</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prediction1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Prediction (Simple Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slr_practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Simple Linear Regression Practice</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R08_prediction_examples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Simple Linear Regression - Examples</span></span></a>
  </div>
</li>
          <li class="px-0"><hr class="sidebar-divider hi "></li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prediction2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Prediction (Multiple Linear Regression)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R09_Multiple_Regression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">R10 multiple regression further concepts</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlr_practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Multiple Linear Regression Practice</span></span></a>
  </div>
</li>
          <li class="px-0"><hr class="sidebar-divider hi "></li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Logistic Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R10_LogisticReg_Extended.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Logistic Regression - Extended Examples</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistic_practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Logistic Regression Practice</span></span></a>
  </div>
</li>
          <li class="px-0"><hr class="sidebar-divider hi "></li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Model Selection and Cross Validation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R11_cv-MSEcomparison.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">cv-extra</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R11_Bias_Variance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Bias Variance Tradeoff</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R11_Model_Selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">R11 Model Selection</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R11_Ridge_LASSO.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">R11: Ridge and Lasso</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cv_practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Cross Validation Practice</span></span></a>
  </div>
</li>
          <li class="px-0"><hr class="sidebar-divider hi "></li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false">
 <span class="menu-text">Bootstrapping</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bootstrap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Bootstrapping</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R12_Bootstrap_Examples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">R13_Bootstrap</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bootstrap_practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Bootstrap Practice</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./RV_summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Random Variable Summary</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#r-squared-and-correlation" id="toc-r-squared-and-correlation" class="nav-link active" data-scroll-target="#r-squared-and-correlation"><span class="header-section-number">29.1</span> R Squared and Correlation</a></li>
  <li><a href="#interaction-plot-for-mtcars---looking-for-an-interaction" id="toc-interaction-plot-for-mtcars---looking-for-an-interaction" class="nav-link" data-scroll-target="#interaction-plot-for-mtcars---looking-for-an-interaction"><span class="header-section-number">29.2</span> Interaction plot for mtcars - looking for an interaction</a></li>
  <li><a href="#multiple-categorical-levels-the-iris-dataset" id="toc-multiple-categorical-levels-the-iris-dataset" class="nav-link" data-scroll-target="#multiple-categorical-levels-the-iris-dataset"><span class="header-section-number">29.3</span> Multiple categorical levels : the iris dataset</a></li>
  <li><a href="#a-model-with-categorical-and-quantitative-variables" id="toc-a-model-with-categorical-and-quantitative-variables" class="nav-link" data-scroll-target="#a-model-with-categorical-and-quantitative-variables"><span class="header-section-number">29.4</span> A Model with categorical and quantitative variables</a></li>
  <li><a href="#interactions-between-categorical-and-quantitative-variables" id="toc-interactions-between-categorical-and-quantitative-variables" class="nav-link" data-scroll-target="#interactions-between-categorical-and-quantitative-variables"><span class="header-section-number">29.5</span> Interactions between categorical and quantitative variables</a></li>
  <li><a href="#more-on-interactions---two-quantitative-predictors" id="toc-more-on-interactions---two-quantitative-predictors" class="nav-link" data-scroll-target="#more-on-interactions---two-quantitative-predictors"><span class="header-section-number">29.6</span> More on Interactions - two quantitative predictors</a></li>
  <li><a href="#mt-cars-polynomial-model" id="toc-mt-cars-polynomial-model" class="nav-link" data-scroll-target="#mt-cars-polynomial-model"><span class="header-section-number">29.7</span> MT Cars polynomial model</a></li>
  <li><a href="#variable-transformations" id="toc-variable-transformations" class="nav-link" data-scroll-target="#variable-transformations"><span class="header-section-number">29.8</span> Variable Transformations</a>
  <ul class="collapse">
  <li><a href="#real-estate-air-conditioning" id="toc-real-estate-air-conditioning" class="nav-link" data-scroll-target="#real-estate-air-conditioning"><span class="header-section-number">29.8.1</span> Real Estate Air Conditioning</a></li>
  </ul></li>
  <li><a href="#multicollinearity" id="toc-multicollinearity" class="nav-link" data-scroll-target="#multicollinearity"><span class="header-section-number">29.9</span> Multicollinearity</a>
  <ul class="collapse">
  <li><a href="#detecting-multicollinearity" id="toc-detecting-multicollinearity" class="nav-link" data-scroll-target="#detecting-multicollinearity"><span class="header-section-number">29.9.1</span> Detecting Multicollinearity</a></li>
  <li><a href="#how-to-handle-multicollinearity" id="toc-how-to-handle-multicollinearity" class="nav-link" data-scroll-target="#how-to-handle-multicollinearity"><span class="header-section-number">29.9.2</span> How to handle Multicollinearity</a></li>
  <li><a href="#a-data-example" id="toc-a-data-example" class="nav-link" data-scroll-target="#a-data-example"><span class="header-section-number">29.9.3</span> A Data Example</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">R10 multiple regression further concepts</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Brian Powers </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 31, 2025</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="r-squared-and-correlation" class="level2" data-number="29.1">
<h2 data-number="29.1" class="anchored" data-anchor-id="r-squared-and-correlation"><span class="header-section-number">29.1</span> R Squared and Correlation</h2>
<p>Consider a simple linear model on mtcars:</p>
<p><span class="math display">\[ hp = \beta_0 + \beta_1 wt  + \epsilon\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>mt.fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(hp <span class="sc">~</span> <span class="dv">1</span><span class="sc">+</span>wt, <span class="at">data=</span>mtcars)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mt.fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = hp ~ 1 + wt, data = mtcars)

Residuals:
    Min      1Q  Median      3Q     Max 
-83.430 -33.596 -13.587   7.913 172.030 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   -1.821     32.325  -0.056    0.955    
wt            46.160      9.625   4.796 4.15e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 52.44 on 30 degrees of freedom
Multiple R-squared:  0.4339,    Adjusted R-squared:  0.4151 
F-statistic:    23 on 1 and 30 DF,  p-value: 4.146e-05</code></pre>
</div>
</div>
<p><span class="math inline">\(R^2 = 0.4339\)</span></p>
<p>What is the sample correlation between wt and hp? We use “r” to refer to this statistic.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(mtcars<span class="sc">$</span>wt, mtcars<span class="sc">$</span>hp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6587479</code></pre>
</div>
</div>
<p>And if we square that</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(mtcars<span class="sc">$</span>wt, mtcars<span class="sc">$</span>hp)<span class="sc">^</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4339488</code></pre>
</div>
</div>
<p>In general, <span class="math inline">\(R^2\)</span> is the correlation between <span class="math inline">\(\hat{y}_i\)</span> and <span class="math inline">\(y_i\)</span>. So for a multiple regression model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>mt.fit2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(qsec <span class="sc">~</span> <span class="dv">1</span><span class="sc">+</span>disp <span class="sc">+</span> wt <span class="sc">+</span> hp, <span class="at">data=</span>mtcars)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mt.fit2)<span class="sc">$</span>r.sq</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6808292</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mtcars<span class="sc">$</span>qsec, <span class="fu">predict</span>(mt.fit2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(mtcars<span class="sc">$</span>qsec, <span class="fu">predict</span>(mt.fit2))<span class="sc">^</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6808292</code></pre>
</div>
</div>
</section>
<section id="interaction-plot-for-mtcars---looking-for-an-interaction" class="level2" data-number="29.2">
<h2 data-number="29.2" class="anchored" data-anchor-id="interaction-plot-for-mtcars---looking-for-an-interaction"><span class="header-section-number">29.2</span> Interaction plot for mtcars - looking for an interaction</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(interactions)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co">#In the mtcars dataset, am and vs are simply numerical variable</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="co"># I want to treat them as categorical variables - aka "factor variables"</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>mtcars<span class="sc">$</span>am <span class="ot">&lt;-</span> <span class="fu">factor</span>(mtcars<span class="sc">$</span>am)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>mtcars<span class="sc">$</span>vs <span class="ot">&lt;-</span> <span class="fu">factor</span>(mtcars<span class="sc">$</span>vs)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>mt.fit.cat <span class="ot">&lt;-</span> <span class="fu">lm</span>(qsec <span class="sc">~</span> <span class="dv">1</span><span class="sc">+</span> am <span class="sc">*</span> vs , <span class="at">data=</span>mtcars)</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="fu">cat_plot</span>(mt.fit.cat, <span class="at">pred=</span><span class="st">"vs"</span>, <span class="at">modx=</span><span class="st">"am"</span>, <span class="at">geom=</span><span class="st">"line"</span>, <span class="at">plot.points=</span><span class="cn">TRUE</span>, <span class="at">data=</span>mtcars, <span class="at">interval=</span>F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The fact that these are parallel indicates that there is no measurable interaction - the effects of engine shape and transmission type seem to be additive. We also see that when we look at the model output:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mt.fit.cat)<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Estimate Std. Error    t value     Pr(&gt;|t|)
(Intercept) 17.14250000  0.3049732 56.2098626 2.443930e-30
am1         -1.34583333  0.5282290 -2.5478216 1.661442e-02
vs1          2.82464286  0.5024460  5.6217837 5.087630e-06
am1:vs1      0.07869048  0.7732481  0.1017661 9.196676e-01</code></pre>
</div>
</div>
<p>The <span class="math inline">\(p\)</span>-value on the am-vs interaction term is really high: that’s .917 indicating that we have no statistical evidence of an interaction. In other words, the inclusion of an interaction term in the model is not statistically justified.</p>
</section>
<section id="multiple-categorical-levels-the-iris-dataset" class="level2" data-number="29.3">
<h2 data-number="29.3" class="anchored" data-anchor-id="multiple-categorical-levels-the-iris-dataset"><span class="header-section-number">29.3</span> Multiple categorical levels : the iris dataset</h2>
<p>The iris dataset is somewhat famous - we have 50 samples from each of three iris species: Setosa, Versicolor and Virginica. Four characteristics are measured: Sepal length &amp; width, and Petal length &amp; width.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(iris)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1          5.1         3.5          1.4         0.2  setosa
2          4.9         3.0          1.4         0.2  setosa
3          4.7         3.2          1.3         0.2  setosa
4          4.6         3.1          1.5         0.2  setosa
5          5.0         3.6          1.4         0.2  setosa
6          5.4         3.9          1.7         0.4  setosa</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#fix the factor leveling just in case</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>iris<span class="sc">$</span>Species <span class="ot">&lt;-</span> <span class="fu">factor</span>(iris<span class="sc">$</span>Species, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"setosa"</span>, <span class="st">"versicolor"</span>, <span class="st">"virginica"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Species is a categorical (factor) variable with three values. In a case like this we still need a numerical encoding of the categorical variable. But using 0, 1 and 2 would be problematic for two reasons. First it implies a progression - an ordering - across the three categorical levels. Secondly, it implies that the effect moving from level 0 to 1 is the same effect of moving from level 1 to level 2.</p>
<p>The proper way to model such a situation is to identify one of the categorical levels (values) to be a “baseline”. R will do this for you alphabetically. In this case setosa is the first alphabetically. Then we create a dummy (indicator) variable for each of the remaining levels. Again - this is automatically done for us by R.</p>
<p>If we were to predict sepal length based only on species, the model would look like this: <span class="math display">\[Y_i = \beta_0 + \beta_1 X_{i,1} + \beta_2 X_{i,2} + \epsilon\]</span> The three cases are handled by the indicator variables as follows:</p>
<pre><code>Species       X_1     X2   
-------------------------
setosa        0       0
versicolor    1       0
virginica     0       1</code></pre>
<p>The model fit is easy in R.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>sepal.fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(Sepal.Length <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> Species, <span class="at">data=</span>iris)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sepal.fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Sepal.Length ~ 1 + Species, data = iris)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.6880 -0.3285 -0.0060  0.3120  1.3120 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         5.0060     0.0728  68.762  &lt; 2e-16 ***
Speciesversicolor   0.9300     0.1030   9.033 8.77e-16 ***
Speciesvirginica    1.5820     0.1030  15.366  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5148 on 147 degrees of freedom
Multiple R-squared:  0.6187,    Adjusted R-squared:  0.6135 
F-statistic: 119.3 on 2 and 147 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><span class="math display">\[\hat{Y} = 5.0060 + .93 X_{vers} + 1.582 X_{vir}\]</span> - For a setosa variety, <span class="math inline">\(X_1=0, X_2=0\)</span> so the predicted sepal length is just 5.006 - For versicolor, <span class="math inline">\(X_1=1, X_2=0\)</span> so the predicted length is 5.006+.93=5.936 - For viginica, <span class="math inline">\(X_1=0, X_2=1\)</span> so the predicted length is 5.006 + 1.582 = 6.588</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">aggregate</span>(Sepal.Length <span class="sc">~</span> Species, <span class="at">data=</span>iris, <span class="at">FUN=</span>mean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Species Sepal.Length
1     setosa        5.006
2 versicolor        5.936
3  virginica        6.588</code></pre>
</div>
</div>
<p>In other words, the intercept is the mean response for the baseline, the <span class="math inline">\(\beta_1, \beta_2\)</span> coefficients are the mean difference between each other case and the baseline.</p>
<p>If you wanted versicolor to be the baseline instead you can refactor your variable</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>iris<span class="sc">$</span>Species <span class="ot">&lt;-</span> <span class="fu">factor</span>(iris<span class="sc">$</span>Species, </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"versicolor"</span>,<span class="st">"setosa"</span>,<span class="st">"virginica"</span>))</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>sepal.fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(Sepal.Length <span class="sc">~</span> <span class="dv">1</span><span class="sc">+</span>Species, <span class="at">data=</span>iris)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sepal.fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Sepal.Length ~ 1 + Species, data = iris)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.6880 -0.3285 -0.0060  0.3120  1.3120 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        5.9360     0.0728  81.536  &lt; 2e-16 ***
Speciessetosa     -0.9300     0.1030  -9.033 8.77e-16 ***
Speciesvirginica   0.6520     0.1030   6.333 2.77e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5148 on 147 degrees of freedom
Multiple R-squared:  0.6187,    Adjusted R-squared:  0.6135 
F-statistic: 119.3 on 2 and 147 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>If you are curious about the dummy variable encoding that R is doing, you can look at the “model matrix”</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">model.matrix</span>(sepal.fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>But I don’t want to refactor the variable, so I’m going to revert the dataset to its default factoring.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(iris)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="a-model-with-categorical-and-quantitative-variables" class="level2" data-number="29.4">
<h2 data-number="29.4" class="anchored" data-anchor-id="a-model-with-categorical-and-quantitative-variables"><span class="header-section-number">29.4</span> A Model with categorical and quantitative variables</h2>
<p>If we were attempting to predict Sepal Length from Petal Length and Species, a model might look like this: <span class="math display">\[Sepal.L = \beta_0 + \beta_1 Species_{Vers} + \beta_2 Species_{Vir} + \beta_3 Petal.L + \epsilon\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Sepal.Length <span class="sc">~</span> Petal.Length, <span class="at">data=</span>iris, <span class="at">col=</span>iris<span class="sc">$</span>Species, <span class="at">pch=</span><span class="dv">16</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>A fitted model (without an interaction) would look like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>sepal.fit1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Sepal.Length <span class="sc">~</span> <span class="dv">1</span><span class="sc">+</span>Species<span class="sc">+</span>Petal.Length, <span class="at">data=</span>iris)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sepal.fit1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Sepal.Length ~ 1 + Species + Petal.Length, data = iris)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.75310 -0.23142 -0.00081  0.23085  1.03100 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        3.68353    0.10610  34.719  &lt; 2e-16 ***
Speciesversicolor -1.60097    0.19347  -8.275 7.37e-14 ***
Speciesvirginica  -2.11767    0.27346  -7.744 1.48e-12 ***
Petal.Length       0.90456    0.06479  13.962  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.338 on 146 degrees of freedom
Multiple R-squared:  0.8367,    Adjusted R-squared:  0.8334 
F-statistic: 249.4 on 3 and 146 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Let’s just interpret the coefficients for a moment:</p>
<p>First off, setosa is the baseline case. The coefficient of Petal length is 0.90456; this means that controlling for species (i.e.&nbsp;holding species constant) a 1 cm increase in Petal Length is associated with a .90456 cm average increase in Sepal Length. <span class="math display">\[\hat{sepal.L}_{set} = 3.68 + .906 petal.L\]</span></p>
<p>For the versicolor coefficient, -1.60097 is interpreted as the average difference in sepal length between a versicolor compared to a setosa iris, controlling for petal length. <span class="math display">\[\hat{sepal.L}_{vers} = (3.68 -1.6) + .906 petal.L\]</span></p>
<p>I’m not going to check the model assumptions at the moment because that’s not my primary focus. I want to plot the model with the quantitative and categorical predictor:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">interact_plot</span>( <span class="fu">lm</span>(Sepal.Length <span class="sc">~</span> Species<span class="sc">+</span>Petal.Length, <span class="at">data=</span>iris), <span class="at">pred=</span>Petal.Length, <span class="at">modx=</span>Species, <span class="at">plot.points=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>You can see clearly that the model fit encodes three parallel lines. We can get the linear equations by writing out the cases. Take setosa first: <span class="math display">\[\hat{Sepal.L}_{Set} = 3.68 + 0.90456 Petal.L\]</span> For versicolor we have <span class="math display">\[\hat{Sepal.L}_{Vers} = 3.68 - 1.6 + 0.90456 Petal.L = 2.08 + .90456 Petal.L\]</span></p>
<p>For virginica <span class="math display">\[\hat{Sepal.L}_{Vers} = 3.68 - 2.12 + 0.90456 Petal.L = 1.56 + .90456 Petal.L\]</span></p>
</section>
<section id="interactions-between-categorical-and-quantitative-variables" class="level2" data-number="29.5">
<h2 data-number="29.5" class="anchored" data-anchor-id="interactions-between-categorical-and-quantitative-variables"><span class="header-section-number">29.5</span> Interactions between categorical and quantitative variables</h2>
<p>Adding an interaction between the categorical predictor and the quantitative predictor allows more model flexibility. It allows for different intercepts <em>and</em> different slopes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>iris.fit<span class="ot">&lt;-</span><span class="fu">lm</span>(Sepal.Length <span class="sc">~</span> <span class="dv">1</span><span class="sc">+</span> Petal.Length <span class="sc">+</span> Species <span class="sc">+</span> Petal.Length<span class="sc">:</span>Species, <span class="at">data=</span>iris)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="co"># or I can use 1 + Petal.Length * Species</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="fu">interact_plot</span>(iris.fit, <span class="at">pred=</span>Petal.Length, <span class="at">modx=</span>Species, <span class="at">plot.points=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Looking at the model summary tells us which of the interactions are statistically supported.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(iris.fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Sepal.Length ~ 1 + Petal.Length + Species + Petal.Length:Species, 
    data = iris)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.73479 -0.22785 -0.03132  0.24375  0.93608 

Coefficients:
                               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                      4.2132     0.4074  10.341  &lt; 2e-16 ***
Petal.Length                     0.5423     0.2768   1.959  0.05200 .  
Speciesversicolor               -1.8056     0.5984  -3.017  0.00302 ** 
Speciesvirginica                -3.1535     0.6341  -4.973 1.85e-06 ***
Petal.Length:Speciesversicolor   0.2860     0.2951   0.969  0.33405    
Petal.Length:Speciesvirginica    0.4534     0.2901   1.563  0.12029    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.3365 on 144 degrees of freedom
Multiple R-squared:  0.8405,    Adjusted R-squared:  0.8349 
F-statistic: 151.7 on 5 and 144 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>In this case neither of them.</p>
<p>The interpretation of these interaction coefficients gives us an adjustment to the slope on <code>Petal.Length</code>. Here’s the full model with coefficient estimates (rounded):</p>
<p><span class="math display">\[\hat{Sepal.L} = 4.2 + .54Petal.L + -1.8 Species_{Ver} - \\ 3.2 Species_{Vir}+0.29Petal.L\cdot Species_{Ver} + .45 Petal.L \cdot Species_{Vir}\]</span></p>
<p>The indicator variables <span class="math inline">\(Species_{Ver}\)</span> and <span class="math inline">\(Species_{Vir}\)</span> are (0,0) for setosa, (1,0) for versicolor and (0,1) for virginica.</p>
<p>For instance, the model for Setosa would be:</p>
<p><span class="math display">\[\hat{Sepal.L}_{Vers} = 4.2 + .54Petal.L\]</span> For the versicolor two more coefficients will play a part: <span class="math display">\[\hat{Sepal.L}_{Ver} = 4.2 + .54Petal.L + -1.8(1) +0.29Petal.L(1)\]</span> Which simplifies to <span class="math display">\[\hat{Sepal.L}_{Ver} = 2.4 + .83 Petal.L\]</span> This is the linear equation for the orange dotted line above. We could do the same for virginica but the idea is the same.</p>
<p>So the coefficients of the interaction terms can be interpreted as the difference in slope between the base case (versicolor) and the other cases (setosa or virginica).</p>
<p>That is how we use interactions between categorical variables and quantitative variables.</p>
<p>You can actually calculate these coefficients by subsetting the data into three species and fitting three linear models!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">lm</span>(Sepal.Length <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> Petal.Length, <span class="at">data=</span><span class="fu">subset</span>(iris, Species<span class="sc">==</span><span class="st">"setosa"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept) Petal.Length 
   4.2131682    0.5422926 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">lm</span>(Sepal.Length <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> Petal.Length, <span class="at">data=</span><span class="fu">subset</span>(iris, Species<span class="sc">==</span><span class="st">"versicolor"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept) Petal.Length 
    2.407523     0.828281 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">lm</span>(Sepal.Length <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> Petal.Length, <span class="at">data=</span><span class="fu">subset</span>(iris, Species<span class="sc">==</span><span class="st">"virginica"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept) Petal.Length 
   1.0596591    0.9957386 </code></pre>
</div>
</div>
<p>The coefficient estimate for the interaction term Petal.Length:Speciessetosa is</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fl">0.5422926</span> <span class="sc">-</span> <span class="fl">0.828281</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.2859884</code></pre>
</div>
</div>
</section>
<section id="more-on-interactions---two-quantitative-predictors" class="level2" data-number="29.6">
<h2 data-number="29.6" class="anchored" data-anchor-id="more-on-interactions---two-quantitative-predictors"><span class="header-section-number">29.6</span> More on Interactions - two quantitative predictors</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(interactions)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>An interaction of two quantitative variables <span class="math inline">\(X1\)</span> and <span class="math inline">\(X2\)</span> would allow for a model that looks something like this:</p>
<p><span class="math display">\[ Y = 10 + 5X1 + 3X2 - 2 X1 \times X2 + \epsilon\]</span></p>
<p>This describes a hyperbolic paraboloid</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="https://mathcurve.com/surfaces.gb/paraboloidhyperbolic/ph-droites.gif" class="img-fluid"></p>
</div>
</div>
<p>An interaction between two quantitative variables is one form of a non-additive relationship with the response variable.</p>
<p>Here is a dataset where the linear model includes an interaction between two continuous variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>states <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(state.x77)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(states)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Population        Income       Illiteracy       Life Exp    
 Min.   :  365   Min.   :3098   Min.   :0.500   Min.   :67.96  
 1st Qu.: 1080   1st Qu.:3993   1st Qu.:0.625   1st Qu.:70.12  
 Median : 2838   Median :4519   Median :0.950   Median :70.67  
 Mean   : 4246   Mean   :4436   Mean   :1.170   Mean   :70.88  
 3rd Qu.: 4968   3rd Qu.:4814   3rd Qu.:1.575   3rd Qu.:71.89  
 Max.   :21198   Max.   :6315   Max.   :2.800   Max.   :73.60  
     Murder          HS Grad          Frost             Area       
 Min.   : 1.400   Min.   :37.80   Min.   :  0.00   Min.   :  1049  
 1st Qu.: 4.350   1st Qu.:48.05   1st Qu.: 66.25   1st Qu.: 36985  
 Median : 6.850   Median :53.25   Median :114.50   Median : 54277  
 Mean   : 7.378   Mean   :53.11   Mean   :104.46   Mean   : 70736  
 3rd Qu.:10.675   3rd Qu.:59.15   3rd Qu.:139.75   3rd Qu.: 81163  
 Max.   :15.100   Max.   :67.30   Max.   :188.00   Max.   :566432  </code></pre>
</div>
</div>
<p>First I want to fit a model that does not include an interaction term.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>fit.noi <span class="ot">&lt;-</span> <span class="fu">lm</span>(Income <span class="sc">~</span> Illiteracy <span class="sc">+</span> Murder <span class="sc">+</span> <span class="st">`</span><span class="at">HS Grad</span><span class="st">`</span>, <span class="at">data =</span> states)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit.noi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Income ~ Illiteracy + Murder + `HS Grad`, data = states)

Residuals:
     Min       1Q   Median       3Q      Max 
-1068.21  -274.66   -40.47   182.69  1203.82 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  2017.96     750.10   2.690 0.009917 ** 
Illiteracy   -176.84     187.25  -0.944 0.349919    
Murder         30.48      26.70   1.141 0.259591    
`HS Grad`      45.19      11.51   3.925 0.000288 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 490.1 on 46 degrees of freedom
Multiple R-squared:  0.4028,    Adjusted R-squared:  0.3638 
F-statistic: 10.34 on 3 and 46 DF,  p-value: 2.551e-05</code></pre>
</div>
</div>
<p>The interaction term can be added to the formula explicitly by including an addition <code>Illiteracy:Murder</code> term, or just use the asterisk to include the interaction and both single terms as well.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>fiti <span class="ot">&lt;-</span> <span class="fu">lm</span>(Income <span class="sc">~</span> Illiteracy <span class="sc">*</span> Murder <span class="sc">+</span> <span class="st">`</span><span class="at">HS Grad</span><span class="st">`</span>, <span class="at">data =</span> states)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fiti)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Income ~ Illiteracy * Murder + `HS Grad`, data = states)

Residuals:
    Min      1Q  Median      3Q     Max 
-916.27 -244.42   28.42  228.14 1221.16 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        1414.46     737.84   1.917  0.06160 .  
Illiteracy          753.07     385.90   1.951  0.05724 .  
Murder              130.60      44.67   2.923  0.00540 ** 
`HS Grad`            40.76      10.92   3.733  0.00053 ***
Illiteracy:Murder   -97.04      35.86  -2.706  0.00958 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 459.5 on 45 degrees of freedom
Multiple R-squared:  0.4864,    Adjusted R-squared:  0.4407 
F-statistic: 10.65 on 4 and 45 DF,  p-value: 3.689e-06</code></pre>
</div>
</div>
<p>The interactions between variables can be explored using interaction plots:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">interact_plot</span>(fiti, <span class="at">pred =</span> Illiteracy, <span class="at">modx =</span> Murder)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The interaction plot takes the other quantitative variable (HS Grad) and sets its value to be the mean (53.11). Three lines are given here indicating how the line changes as the Murder variable may vary from its average mean value.</p>
<p><span class="math display">\[\hat{Income} = 1414.46+753 Ill + 130.60 Mur + 40.76(53.11) -97.04 Ill \times Mur\]</span> You can see that as the murder rate increases the effect of illiteracy on income changes. This is reflected in the negative value for the interaction. In this case the Mur variable is continuous rather than categorical. The interpretation of the coefficient on the interaction term is a little more tricky to put into words. That’s beyond this course.</p>
<p>The important take-away here is that the interaction term is statistically significant, so we have strong evidence from the data that there is a real interaction in the model. The average effect of Illiteracy and Murder rate on per capita income is not purely additive.</p>
</section>
<section id="mt-cars-polynomial-model" class="level2" data-number="29.7">
<h2 data-number="29.7" class="anchored" data-anchor-id="mt-cars-polynomial-model"><span class="header-section-number">29.7</span> MT Cars polynomial model</h2>
<p>Let’s briefly compare a linear model with a second order model</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mpg<span class="sc">~</span>hp, <span class="at">data=</span>mtcars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>mtcars.pow1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> hp, <span class="at">data=</span>mtcars)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mtcars.pow1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ 1 + hp, data = mtcars)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.7121 -2.1122 -0.8854  1.5819  8.2360 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 30.09886    1.63392  18.421  &lt; 2e-16 ***
hp          -0.06823    0.01012  -6.742 1.79e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.863 on 30 degrees of freedom
Multiple R-squared:  0.6024,    Adjusted R-squared:  0.5892 
F-statistic: 45.46 on 1 and 30 DF,  p-value: 1.788e-07</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mtcars.pow1, <span class="at">which=</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-26-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>mtcars.pow2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> hp <span class="sc">+</span> <span class="fu">I</span>(hp<span class="sc">^</span><span class="dv">2</span>), <span class="at">data=</span>mtcars)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mtcars.pow2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ 1 + hp + I(hp^2), data = mtcars)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.5512 -1.6027 -0.6977  1.5509  8.7213 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  4.041e+01  2.741e+00  14.744 5.23e-15 ***
hp          -2.133e-01  3.488e-02  -6.115 1.16e-06 ***
I(hp^2)      4.208e-04  9.844e-05   4.275 0.000189 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.077 on 29 degrees of freedom
Multiple R-squared:  0.7561,    Adjusted R-squared:  0.7393 
F-statistic: 44.95 on 2 and 29 DF,  p-value: 1.301e-09</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mtcars.pow2, <span class="at">which=</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>For the moment let’s consider a third order polynomial just to see if the linearity is better satisfied.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>mtcars.pow3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> hp <span class="sc">+</span> <span class="fu">I</span>(hp<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(hp<span class="sc">^</span><span class="dv">3</span>), <span class="at">data=</span>mtcars)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mtcars.pow3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ 1 + hp + I(hp^2) + I(hp^3), data = mtcars)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.8605 -1.3972 -0.5736  1.6461  9.0738 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  4.422e+01  5.961e+00   7.419 4.43e-08 ***
hp          -2.945e-01  1.178e-01  -2.500   0.0185 *  
I(hp^2)      9.115e-04  6.863e-04   1.328   0.1949    
I(hp^3)     -8.701e-07  1.204e-06  -0.722   0.4760    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.103 on 28 degrees of freedom
Multiple R-squared:  0.7606,    Adjusted R-squared:  0.7349 
F-statistic: 29.65 on 3 and 28 DF,  p-value: 7.769e-09</code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mtcars.pow3, <span class="at">which=</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="variable-transformations" class="level2" data-number="29.8">
<h2 data-number="29.8" class="anchored" data-anchor-id="variable-transformations"><span class="header-section-number">29.8</span> Variable Transformations</h2>
<p>Variable transformations can be effective at remedying violated regression assumptions. Briefly here are the assumptions:</p>
<ul>
<li>The error term has a normal distribution</li>
<li>The response variable has a linear relationship with the predictors. In other words, the errors have zero mean</li>
<li>The error term has constant variance</li>
<li>The errors are independent.</li>
</ul>
<p>The fourth assumption is hard to check, but the first three can be checked with diagnostic plots of the residuals.</p>
<p>Transformation of either a predictor variable or the response variable may be appropriate, often with theoretical justification. But first let’s explore the effect of variable transformation.</p>
<p>Here is some left-skewed data</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>left.skew.data <span class="ot">&lt;-</span> <span class="fu">rbeta</span>(<span class="dv">60</span>, <span class="dv">2</span>, <span class="dv">1</span>)<span class="sc">*</span><span class="dv">10</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(left.skew.data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>And here are histograms of the data taken to different powers</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">log</span>(left.skew.data), <span class="at">main=</span><span class="st">"Log transform"</span>)</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>((left.skew.data)<span class="sc">^</span>.<span class="dv">5</span>, <span class="at">main=</span><span class="st">"square root transform"</span>)</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>((left.skew.data)<span class="sc">^</span><span class="dv">2</span>, <span class="at">main=</span><span class="st">"squaring"</span>)</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>((left.skew.data)<span class="sc">^</span><span class="dv">3</span>, <span class="at">main=</span><span class="st">"cubing"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>You can see that squaring the values give us a more symmetric distribution. Generally speaking, if you have left-skewed data, raising your values to a power <span class="math inline">\(&gt;1\)</span> can do this for you.</p>
<p>On the other hand, here is some right-skewed data - an exponential population</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>right.skew.data <span class="ot">&lt;-</span> <span class="fu">rexp</span>(<span class="dv">60</span>, <span class="dv">2</span>)</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(right.skew.data, <span class="at">breaks=</span><span class="dv">25</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">log</span>(right.skew.data), <span class="at">main=</span><span class="st">"log"</span>)</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>((right.skew.data)<span class="sc">^</span>.<span class="dv">5</span>, <span class="at">main=</span><span class="st">"sqrt"</span>)</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>((right.skew.data)<span class="sc">^</span><span class="dv">2</span>, <span class="at">main=</span><span class="st">"Square"</span>, <span class="at">breaks=</span><span class="dv">20</span>)</span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>((right.skew.data)<span class="sc">^</span><span class="dv">3</span>, <span class="at">main=</span><span class="st">"cube"</span>, <span class="at">breaks=</span><span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>A right skew is amplified by taking your data to a higher power, but square roots and log transformations can make your data more symmetric and sometimes more normally distributed.</p>
<p>Variable transformations can often be effective means to remedy violated regression assumptions.</p>
<section id="real-estate-air-conditioning" class="level3" data-number="29.8.1">
<h3 data-number="29.8.1" class="anchored" data-anchor-id="real-estate-air-conditioning"><span class="header-section-number">29.8.1</span> Real Estate Air Conditioning</h3>
<p>The real estate data is in the <code>realestate.txt</code> file.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>real.estate <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"data/realestate.txt"</span>, <span class="at">header=</span>T)</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>real.estate<span class="sc">$</span>Air <span class="ot">&lt;-</span> <span class="fu">factor</span>(real.estate<span class="sc">$</span>Air)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>While there are many variables, we’ll focus only on three: - Y = sale price of the home (in 1000s of dollars) - X1 = square footage of the home (in 1000s of sqft) - X2 = whether or not the home has air conditioning</p>
<p>The interaction model is <span class="math display">\[Y_i = \beta_0 + \beta_1 X_{i,1} + \beta_2 X_{i,2} + \beta_3 X_{i,1}X_{i,2} + \epsilon_i\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>real.fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(SalePrice <span class="sc">~</span> <span class="dv">1</span><span class="sc">+</span>SqFeet<span class="sc">*</span>Air, <span class="at">data=</span>real.estate)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(interactions)</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a><span class="fu">interact_plot</span>(real.fit, <span class="at">pred=</span>SqFeet, <span class="at">modx=</span>Air, <span class="at">plot.points =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(real.fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = SalePrice ~ 1 + SqFeet * Air, data = real.estate)

Residuals:
    Min      1Q  Median      3Q     Max 
-248.01  -37.13   -7.80   22.25  381.92 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   -3.218     30.085  -0.107 0.914871    
SqFeet       104.902     15.748   6.661 6.96e-11 ***
Air1         -78.868     32.663  -2.415 0.016100 *  
SqFeet:Air1   55.888     16.580   3.371 0.000805 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 77.01 on 517 degrees of freedom
Multiple R-squared:  0.6887,    Adjusted R-squared:  0.6869 
F-statistic: 381.2 on 3 and 517 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(real.fit, <span class="at">which=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-34-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-34-3.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>There is strong evidence supporting the interaction in the model, and both preditors are strong predictors of sale price. However there are two big problems. One is the residuals spread is not constant, and the residuals do not seem to be normally distributed. The non constant spread can be seen in the plot</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">interact_plot</span>(real.fit, <span class="at">pred=</span>SqFeet, <span class="at">modx=</span>Air, <span class="at">plot.points =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">resid</span>(real.fit))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-35-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>the residuals are unimodal but the right tail is too long - this is shown in the QQ plot but more obviously emphasized in the histogram above.</p>
<p>When large values of <span class="math inline">\(y\)</span> have higher variance than low values of <span class="math inline">\(y\)</span> a log transformation of the response variable will often fix the problem. This is because error is not in absolute term but rather relative to the magnitude of <span class="math inline">\(y\)</span>. Logs fix this mathematically.</p>
<p>We’ll transform Sale Price in the model: <span class="math display">\[\ln Y_i = \beta_0 + \beta_1 X_{i,1} + \beta_2 X_{i,2} + \beta_3 X_{i,1}X_{i,2} + \epsilon_i\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>real.fit.log <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(SalePrice) <span class="sc">~</span> <span class="dv">1</span><span class="sc">+</span>SqFeet<span class="sc">*</span>Air, <span class="at">data=</span>real.estate)</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(real.fit.log)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(SalePrice) ~ 1 + SqFeet * Air, data = real.estate)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.73816 -0.13955 -0.02114  0.11740  0.82106 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  4.32846    0.08813  49.113   &lt;2e-16 ***
SqFeet       0.46808    0.04613  10.146   &lt;2e-16 ***
Air1         0.11522    0.09569   1.204    0.229    
SqFeet:Air1  0.02202    0.04857   0.453    0.650    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2256 on 517 degrees of freedom
Multiple R-squared:  0.7274,    Adjusted R-squared:  0.7259 
F-statistic: 459.9 on 3 and 517 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(real.fit.log, <span class="at">which=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-36-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">interact_plot</span>(real.fit.log, <span class="at">pred=</span>SqFeet, <span class="at">modx=</span>Air, <span class="at">plot.points =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Using data real.estate from global environment. This could cause incorrect
results if real.estate has been altered since the model was fit. You can
manually provide the data to the "data =" argument.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-36-3.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">resid</span>(real.fit.log))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-36-4.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The predictor variable SqFeet also exhibits a right skew</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(real.estate<span class="sc">$</span>SqFeet)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In a case like this a linear model may possibly fit better if the predictor is log transformed too. This is worth checking</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>real.estate<span class="sc">$</span>logSqFeet <span class="ot">&lt;-</span> <span class="fu">log</span>(real.estate<span class="sc">$</span>SqFeet)</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>real.fit.log <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(SalePrice) <span class="sc">~</span> <span class="dv">1</span><span class="sc">+</span>logSqFeet<span class="sc">*</span>Air, <span class="at">data=</span>real.estate)</span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(real.fit.log)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(SalePrice) ~ 1 + logSqFeet * Air, data = real.estate)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.58375 -0.13872 -0.01541  0.11524  0.76531 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     4.62997    0.05729  80.811  &lt; 2e-16 ***
logSqFeet       0.97321    0.09119  10.673  &lt; 2e-16 ***
Air1           -0.04867    0.06549  -0.743  0.45770    
logSqFeet:Air1  0.27514    0.09838   2.797  0.00535 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2183 on 517 degrees of freedom
Multiple R-squared:  0.7448,    Adjusted R-squared:  0.7434 
F-statistic: 503.1 on 3 and 517 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(real.fit.log, <span class="at">which=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-38-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">interact_plot</span>(real.fit.log, <span class="at">pred=</span>logSqFeet, <span class="at">modx=</span>Air, <span class="at">plot.points =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Using data real.estate from global environment. This could cause incorrect
results if real.estate has been altered since the model was fit. You can
manually provide the data to the "data =" argument.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-38-3.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">resid</span>(real.fit.log))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-38-4.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The interaction of air conditioning and square feet is brought out more clearly when this transformation is done, as shown in the significance of the predictor. This model also has the strongest <span class="math inline">\(R^2\)</span> of all three models considered.</p>
<p>Let’s consider how this model would estimate / predict the sale price of a 1800 sqft house with air conditioning.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(real.fit.log, <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">logSqFeet =</span> <span class="fu">log</span>(<span class="fl">1.800</span>), <span class="at">Air=</span><span class="st">"1"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
5.315058 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="co">#to conver this to our units, we take e^&lt;this&gt;</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">predict</span>(real.fit.log, <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">logSqFeet =</span> <span class="fu">log</span>(<span class="fl">1.800</span>), <span class="at">Air=</span><span class="st">"1"</span>))</span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
203.3764 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="co">#to convert a 95% confidence interval back to original units, do the same</span></span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a><span class="co">#this is my 95% prediction interval for ONE particular house that is 1800 sqft</span></span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">predict</span>(real.fit.log, <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">logSqFeet =</span> <span class="fu">log</span>(<span class="fl">1.800</span>), <span class="at">Air=</span><span class="st">"1"</span>), <span class="at">interval=</span><span class="st">"prediction"</span>)</span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 203.3764 132.3514 312.5161</code></pre>
</div>
</div>
</section>
</section>
<section id="multicollinearity" class="level2" data-number="29.9">
<h2 data-number="29.9" class="anchored" data-anchor-id="multicollinearity"><span class="header-section-number">29.9</span> Multicollinearity</h2>
<p>When predictor variables exhibit high correlation we call this multicollinearity. This can cause a number of problems which we’ll discuss. First let’s consider some synthetic data where the predictors are perfectly correlated - this is an extreme case.</p>
<p><span class="math display">\[ X_2 = 2.5 X_1-1\]</span> If the true model looks like this: <span class="math display">\[Y = 10 + 2X_1 +.3 X_2 + \epsilon, \quad \epsilon \sim N(0, 4^2)\]</span> We could actually write <span class="math inline">\(X_2\)</span> in terms of <span class="math inline">\(X_1\)</span> or vice versa. For instance, we could substitute in the expression <span class="math inline">\(2.5X_1-1\)</span> and get <span class="math display">\[Y = 10 + 2X_1 + .3(2.5X_1-1) + \epsilon = 9.7 + 2.75X_1 + \epsilon\]</span> Or we could substitute <span class="math inline">\(X_1 = \frac{X_2+1}{2.5}\)</span> and get <span class="math display">\[ Y = 10 + 2\frac{X_2+1}{2.5}+.3X_2+\epsilon = 10.8 + 1.1 X_2+ \epsilon\]</span> Both of these models are perfectly true. The fact is that both would fit the data just as well.</p>
<p>In fact, if your predictors exhibit perfect correlation then R will be unable to properly fit a linear model to the data.</p>
<p>I’ll simulate a sample of size 30.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>X1 <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">30</span>, <span class="dv">10</span>,<span class="dv">20</span>) </span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>X2 <span class="ot">&lt;-</span> <span class="fl">2.5</span> <span class="sc">*</span> X1 <span class="sc">-</span><span class="dv">1</span></span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">&lt;-</span> <span class="dv">10</span><span class="sc">+</span><span class="dv">2</span><span class="sc">*</span>X1<span class="fl">+.3</span><span class="sc">*</span>X2 <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="dv">0</span>, <span class="dv">4</span>)</span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Y<span class="sc">~</span><span class="dv">1</span><span class="sc">+</span>X1<span class="sc">+</span>X2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ 1 + X1 + X2)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.3413 -2.1553 -0.0532  2.5223  5.1597 

Coefficients: (1 not defined because of singularities)
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  11.3450     3.3053   3.432  0.00188 ** 
X1            2.6857     0.2188  12.273 8.74e-13 ***
X2                NA         NA      NA       NA    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.195 on 28 degrees of freedom
Multiple R-squared:  0.8433,    Adjusted R-squared:  0.8377 
F-statistic: 150.6 on 1 and 28 DF,  p-value: 8.738e-13</code></pre>
</div>
</div>
<p>The case of perfect correlation is rare but a strong correlation could certainly arise. I’ll add a little bit of random spice in to the calculation of <span class="math inline">\(X_2\)</span> and we’ll look at the correlation plots.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>X1 <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">30</span>, <span class="dv">10</span>,<span class="dv">20</span>) </span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a>X2 <span class="ot">&lt;-</span> <span class="fl">2.5</span> <span class="sc">*</span> X1 <span class="sc">-</span><span class="dv">1</span> <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">30</span>,<span class="dv">0</span>,<span class="dv">1</span>)</span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">&lt;-</span> <span class="dv">10</span><span class="sc">+</span><span class="dv">2</span><span class="sc">*</span>X1<span class="fl">+.3</span><span class="sc">*</span>X2 <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="dv">0</span>, <span class="dv">4</span>)</span>
<span id="cb92-5"><a href="#cb92-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">data.frame</span>(Y,X1,X2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We can numerically measure the correlation using the <code>cor</code> function</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(<span class="fu">data.frame</span>(Y,X1,X2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           Y        X1        X2
Y  1.0000000 0.8710865 0.8966127
X1 0.8710865 1.0000000 0.9944797
X2 0.8966127 0.9944797 1.0000000</code></pre>
</div>
</div>
<p>If we attempt to fit a linear model this is what we get:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Y<span class="sc">~</span><span class="dv">1</span><span class="sc">+</span>X1<span class="sc">+</span>X2))<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Estimate Std. Error   t value     Pr(&gt;|t|)
(Intercept) 16.339897  3.4972494  4.672214 7.349847e-05
X1          -5.446292  2.1220827 -2.566484 1.613689e-02
X2           3.200272  0.8458235  3.783617 7.822802e-04</code></pre>
</div>
</div>
<p>In the true model the coefficients of <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span> are <span class="math inline">\(2\)</span> and <span class="math inline">\(.3\)</span>. These quite far off! The intercept is way off as well.</p>
<p>I’ll repeat again with newly generated data to see how it differs</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a>X1 <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">30</span>, <span class="dv">10</span>,<span class="dv">20</span>) </span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a>X2 <span class="ot">&lt;-</span> <span class="fl">2.5</span> <span class="sc">*</span> X1 <span class="sc">-</span><span class="dv">1</span> <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">30</span>,<span class="dv">0</span>,<span class="dv">1</span>)</span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">&lt;-</span> <span class="dv">10</span><span class="sc">+</span><span class="dv">2</span><span class="sc">*</span>X1<span class="fl">+.3</span><span class="sc">*</span>X2 <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="dv">0</span>, <span class="dv">4</span>)</span>
<span id="cb97-4"><a href="#cb97-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Y<span class="sc">~</span>X1<span class="sc">+</span>X2))<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Estimate Std. Error    t value    Pr(&gt;|t|)
(Intercept) 11.9418373  4.2513025  2.8089832 0.009126691
X1           3.0977225  1.9737924  1.5694267 0.128195112
X2          -0.2370767  0.7921835 -0.2992699 0.767025684</code></pre>
</div>
</div>
<p>Notice that the coefficient of <span class="math inline">\(X_1\)</span> is now a lot lower (and negative) and the coefficient of <span class="math inline">\(X_2\)</span> is positive now! Furthermore, the <span class="math inline">\(p\)</span>-values for the coefficients are all <span class="math inline">\(&gt;0.05\)</span>. This is common when predictors are highly correlated. Typical problems that you will see when you have multicollinearity are:</p>
<ul>
<li>Parameters of the model become indeterminate</li>
<li>Standard errors of the estimates become large</li>
<li>addition or removal of a predictor can drastically change the coefficients - even flip their signs</li>
<li>it becomes difficult or impossible to interpret the coefficients</li>
<li>predictions risk extrapolation</li>
</ul>
<p>The first two problems are understandable if we think about the extreme case. We actually had three models that were equally valid when we had perfect correlation (ignoring <span class="math inline">\(\epsilon\)</span> for simplicity):</p>
<p><span class="math display">\[Y = 10 + 2X_1 +.3 X_2, \quad Y=9.7 + 2.75X_1, \quad Y=10.8 + 1.1 X_2\]</span> In fact, there are an infinite number of models you could fit that would fit equally well. This means we have no certainty of either of the coefficient values. In fact, the uncertainty of <span class="math inline">\(\beta_1\)</span> and <span class="math inline">\(\beta_2\)</span> affects our uncertainty of <span class="math inline">\(\beta_0\)</span> as well! This causes the standard errors to be large.</p>
<p>What happens when we remove a predictor? I’ll refit the model with only <span class="math inline">\(X_1\)</span> and only <span class="math inline">\(X_2\)</span> to see</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Y<span class="sc">~</span>X1<span class="sc">+</span>X2))<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Estimate Std. Error    t value    Pr(&gt;|t|)
(Intercept) 11.9418373  4.2513025  2.8089832 0.009126691
X1           3.0977225  1.9737924  1.5694267 0.128195112
X2          -0.2370767  0.7921835 -0.2992699 0.767025684</code></pre>
</div>
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Y<span class="sc">~</span>X1))<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Estimate Std. Error  t value     Pr(&gt;|t|)
(Intercept) 12.034186  4.1705844 2.885491 7.441841e-03
X1           2.512754  0.2697257 9.315962 4.491075e-10</code></pre>
</div>
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Y<span class="sc">~</span>X2))<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Estimate Std. Error  t value     Pr(&gt;|t|)
(Intercept) 13.3338353  4.2649971 3.126341 4.099863e-03
X2           0.9941401  0.1128976 8.805676 1.474748e-09</code></pre>
</div>
</div>
<p>Notice that in the models with only 1 predictor the <span class="math inline">\(p\)</span>-value shoots down to close to zero. The standard error shrinks as well. When we have a model with only one of these correlated predictors we can focus on the predictive power of that one predictor and it is not muddied by the influence of the other one.</p>
<p>This leads to the fourth problem. Interpretation of coefficients in a multiple regression model requires us to say something like “holding other variables constant”. But if <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span> exhibit strong correlation in the real world, then it’s not reasonable to hold one constant while changing the other.</p>
<p>What about the fifth problem about extrapolations? Let’s look at the data summaries:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">data.frame</span>(X1,X2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       X1              X2       
 Min.   :10.64   Min.   :25.31  
 1st Qu.:13.36   1st Qu.:33.30  
 Median :15.15   Median :37.10  
 Mean   :15.26   Mean   :37.26  
 3rd Qu.:17.37   3rd Qu.:42.42  
 Max.   :19.03   Max.   :46.84  </code></pre>
</div>
</div>
<p>Our dataset includes <span class="math inline">\(X1\)</span> over the range 10 to 20 roughly, and <span class="math inline">\(X2\)</span> over the range 23 to 50. So one might think that <span class="math inline">\(Y\)</span> could be predicted for any pair of <span class="math inline">\(X1,X2\)</span> values in the range <span class="math inline">\([10,20]\times[25,50]\)</span>. For example, can we predict <span class="math inline">\(\hat{Y}|X_1=11, X_2=48\)</span> ?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a>lmfit <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y<span class="sc">~</span>X1<span class="sc">+</span>X2)</span>
<span id="cb107-2"><a href="#cb107-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(lmfit, <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">X1=</span><span class="dv">11</span>, <span class="at">X2=</span><span class="dv">48</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      1 
34.6371 </code></pre>
</div>
</div>
<p>No problem there. But let’s look again at the data range as a scatterplot</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(X1,X2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-48-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The only data we’ve observed is over thin diagonal strip. Our model is not supported outside of this range, so predicting <span class="math inline">\(Y\)</span> for <span class="math inline">\(X1=11, X2=48\)</span> has a tremendous amount of uncertainty.</p>
<section id="detecting-multicollinearity" class="level3" data-number="29.9.1">
<h3 data-number="29.9.1" class="anchored" data-anchor-id="detecting-multicollinearity"><span class="header-section-number">29.9.1</span> Detecting Multicollinearity</h3>
<p>A simple statistic that measures multicollinearity is the Variance Inflation Factor or VIF. The idea is that we take each predictor and fit a linear model with this predictor as the response and the other predictors as predictors. We measure how strong the coefficient of determination (<span class="math inline">\(R^2\)</span>) is, and calculate <span class="math display">\[VIF_j = \frac{1}{1-R^2_j}\]</span> For instance, in this case we have</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a>rsq <span class="ot">=</span> <span class="fu">summary</span>(<span class="fu">lm</span>(X1<span class="sc">~</span>X2))<span class="sc">$</span>r.square</span>
<span id="cb110-2"><a href="#cb110-2" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>rsq)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 51.80865</code></pre>
</div>
</div>
<p>This is very high - a VIF more than 10 is extremely problematic.</p>
<p>There’s a function in the <code>car</code> package to calculate VIF for all predictors in a model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(lmfit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      X1       X2 
51.80865 51.80865 </code></pre>
</div>
</div>
<p>Note that in this case both predictors have the same VIF. This is because when we regress <span class="math inline">\(X1\)</span> on <span class="math inline">\(X2\)</span> the correlation is the same as if we regress <span class="math inline">\(X2\)</span> on <span class="math inline">\(X1\)</span>.</p>
</section>
<section id="how-to-handle-multicollinearity" class="level3" data-number="29.9.2">
<h3 data-number="29.9.2" class="anchored" data-anchor-id="how-to-handle-multicollinearity"><span class="header-section-number">29.9.2</span> How to handle Multicollinearity</h3>
<p>There are some more advanced methods but probably the simplest method is to remove one of the problematic predictors. In this case we could choose arbitrarily to keep <span class="math inline">\(X1\)</span> or <span class="math inline">\(X2\)</span> in the model and drop the other one. Either choice would be fine.</p>
<p>Note that in the case of multicollinearity this dropping of a redundant variable will not cause <span class="math inline">\(R^2\)</span> to suffer much at all. Observe:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Y<span class="sc">~</span>X1<span class="sc">+</span>X2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X1 + X2)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.4838 -2.3684 -0.4808  1.6046  9.7260 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)  11.9418     4.2513   2.809  0.00913 **
X1            3.0977     1.9738   1.569  0.12820   
X2           -0.2371     0.7922  -0.299  0.76703   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.747 on 27 degrees of freedom
Multiple R-squared:  0.7569,    Adjusted R-squared:  0.7389 
F-statistic: 42.03 on 2 and 27 DF,  p-value: 5.113e-09</code></pre>
</div>
<div class="sourceCode cell-code" id="cb118"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Y<span class="sc">~</span>X1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X1)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.3143 -2.0682 -0.4356  1.2547  9.8196 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  12.0342     4.1706   2.885  0.00744 ** 
X1            2.5128     0.2697   9.316 4.49e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.686 on 28 degrees of freedom
Multiple R-squared:  0.7561,    Adjusted R-squared:  0.7474 
F-statistic: 86.79 on 1 and 28 DF,  p-value: 4.491e-10</code></pre>
</div>
</div>
</section>
<section id="a-data-example" class="level3" data-number="29.9.3">
<h3 data-number="29.9.3" class="anchored" data-anchor-id="a-data-example"><span class="header-section-number">29.9.3</span> A Data Example</h3>
<p>The datafile (<code>wages85.txt</code>) is downloaded from http://lib.stat.cmu.edu/datasets/. It contains 534 observations on 11 variables sampled from the Current Population Survey of 1985. The Current Population Survey (CPS) is used to supplement census information between census years. These data consist of a random sample of 534 persons from the CPS, with information on wages and other characteristics of the workers, including sex, number of years of education, years of work experience, occupational status, region of residence and union membership. We wish to determine whether wages are related to these characteristics. In particular, we are seeking for the following model:</p>
<p><span class="math inline">\(wage = \beta_0 + \beta_1 south + \beta_2 sex + \beta_3 exp + \beta_4 union + \beta_5 age + \beta_6 race_2 + \beta_7 race_3 + \cdots\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a>wages <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"data/wages85.txt"</span>, <span class="at">header=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>But we should understand how the data is encoded. In particular some of the variables are categorical variables: SOUTH, SEX, RACE, SECTOR, MARR, OCCUPATION, UNION. We should convert these to categorical <code>factor</code> type variables rather than numeric.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a>wages<span class="sc">$</span>SOUTH <span class="ot">&lt;-</span> <span class="fu">factor</span>(wages<span class="sc">$</span>SOUTH)</span>
<span id="cb121-2"><a href="#cb121-2" aria-hidden="true" tabindex="-1"></a>wages<span class="sc">$</span>SEX <span class="ot">&lt;-</span> <span class="fu">factor</span>(wages<span class="sc">$</span>SEX)</span>
<span id="cb121-3"><a href="#cb121-3" aria-hidden="true" tabindex="-1"></a>wages<span class="sc">$</span>RACE <span class="ot">&lt;-</span> <span class="fu">factor</span>(wages<span class="sc">$</span>RACE)</span>
<span id="cb121-4"><a href="#cb121-4" aria-hidden="true" tabindex="-1"></a>wages<span class="sc">$</span>SECTOR <span class="ot">&lt;-</span> <span class="fu">factor</span>(wages<span class="sc">$</span>SECTOR)</span>
<span id="cb121-5"><a href="#cb121-5" aria-hidden="true" tabindex="-1"></a>wages<span class="sc">$</span>MARR <span class="ot">&lt;-</span> <span class="fu">factor</span>(wages<span class="sc">$</span>MARR)</span>
<span id="cb121-6"><a href="#cb121-6" aria-hidden="true" tabindex="-1"></a>wages<span class="sc">$</span>OCCUPATION <span class="ot">&lt;-</span> <span class="fu">factor</span>(wages<span class="sc">$</span>OCCUPATION)</span>
<span id="cb121-7"><a href="#cb121-7" aria-hidden="true" tabindex="-1"></a>wages<span class="sc">$</span>UNION <span class="ot">&lt;-</span> <span class="fu">factor</span>(wages<span class="sc">$</span>UNION)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now we can fit the model. Note that with all of these categorical variables we will have a lot of model coefficients. With a sample size of 500+ that’s not a huge concern right now. Anyway, the point is going to be about multicollinearity.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb122"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a><span class="co"># the "." indicates I want to use ALL predictors in the model. No interactions though.</span></span>
<span id="cb122-2"><a href="#cb122-2" aria-hidden="true" tabindex="-1"></a>wage.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(WAGE <span class="sc">~</span> . , <span class="at">data=</span>wages)</span>
<span id="cb122-3"><a href="#cb122-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wage.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = WAGE ~ ., data = wages)

Residuals:
    Min      1Q  Median      3Q     Max 
-11.409  -2.486  -0.631   1.872  35.021 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   2.2781     6.6976   0.340  0.73390    
EDUCATION     0.8128     1.0869   0.748  0.45491    
SOUTH1       -0.5627     0.4198  -1.340  0.18070    
SEX1         -1.9425     0.4194  -4.631 4.60e-06 ***
EXPERIENCE    0.2448     1.0818   0.226  0.82103    
UNION1        1.6017     0.5127   3.124  0.00188 ** 
AGE          -0.1580     1.0809  -0.146  0.88382    
RACE2         0.2314     0.9915   0.233  0.81559    
RACE3         0.8379     0.5745   1.458  0.14532    
OCCUPATION2  -4.0638     0.9159  -4.437 1.12e-05 ***
OCCUPATION3  -3.2682     0.7626  -4.286 2.17e-05 ***
OCCUPATION4  -3.9754     0.8108  -4.903 1.26e-06 ***
OCCUPATION5  -1.3336     0.7289  -1.829  0.06791 .  
OCCUPATION6  -3.2905     0.8005  -4.111 4.59e-05 ***
SECTOR1       1.0409     0.5492   1.895  0.05863 .  
SECTOR2       0.4774     0.9661   0.494  0.62141    
MARR1         0.3005     0.4112   0.731  0.46523    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.282 on 517 degrees of freedom
Multiple R-squared:  0.3265,    Adjusted R-squared:  0.3056 
F-statistic: 15.66 on 16 and 517 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb124"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wage.lm, <span class="at">which=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: not plotting observations with leverage one:
  444</code></pre>
</div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-54-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-54-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Without going into the summary, it’s clear that variance increases with predicted wage; this is a good indication that a log transformation or square root transformation of the response variable could be useful. In fact that could even fix the non normality of residuals</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb126"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb126-1"><a href="#cb126-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">resid</span>(wage.lm), <span class="at">breaks=</span><span class="dv">50</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-55-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a>wage.log.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(WAGE) <span class="sc">~</span> ., <span class="at">data=</span>wages)</span>
<span id="cb127-2"><a href="#cb127-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wage.log.lm, <span class="at">which=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-56-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-56-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb128"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb128-1"><a href="#cb128-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">resid</span>(wage.log.lm), <span class="at">breaks=</span><span class="dv">50</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-56-3.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The log transform fixed both problems. So instead of predicting wage, we’ll predict log(wage). But let’s look at the summary output.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wage.log.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(WAGE) ~ ., data = wages)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.36167 -0.27926  0.00049  0.27957  1.79838 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.54415    0.66955   2.306 0.021491 *  
EDUCATION    0.12525    0.10865   1.153 0.249530    
SOUTH1      -0.09290    0.04197  -2.214 0.027291 *  
SEX1        -0.21812    0.04193  -5.202 2.85e-07 ***
EXPERIENCE   0.06799    0.10814   0.629 0.529813    
UNION1       0.21178    0.05126   4.132 4.20e-05 ***
AGE         -0.05858    0.10806  -0.542 0.587963    
RACE2       -0.03345    0.09912  -0.338 0.735876    
RACE3        0.07973    0.05743   1.388 0.165636    
OCCUPATION2 -0.36440    0.09156  -3.980 7.88e-05 ***
OCCUPATION3 -0.20964    0.07624  -2.750 0.006171 ** 
OCCUPATION4 -0.38345    0.08105  -4.731 2.89e-06 ***
OCCUPATION5 -0.05278    0.07287  -0.724 0.469223    
OCCUPATION6 -0.26555    0.08002  -3.318 0.000969 ***
SECTOR1      0.11532    0.05491   2.100 0.036186 *  
SECTOR2      0.09296    0.09658   0.962 0.336262    
MARR1        0.06335    0.04111   1.541 0.123899    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4281 on 517 degrees of freedom
Multiple R-squared:  0.3617,    Adjusted R-squared:  0.342 
F-statistic: 18.31 on 16 and 517 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>By looking at the model summary, the R-squared value of 0.362 is not bad for a cross sectional data of 534 observations. The F-value is highly significant implying that all the explanatory variables together significantly explain the log of wages. However, coming to the individual regression coefficients, it is seen that as many as five variables (race, education, experience, age, marriage) are not statistically significant.</p>
<p>For further diagnosis of the problem, let us first look at the pair-wise correlation among the numerical variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb131"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb131-1"><a href="#cb131-1" aria-hidden="true" tabindex="-1"></a>X<span class="ot">&lt;-</span>wages[,<span class="fu">c</span>(<span class="st">"EDUCATION"</span>,<span class="st">"EXPERIENCE"</span>,<span class="st">"WAGE"</span>,<span class="st">"AGE"</span>)]</span>
<span id="cb131-2"><a href="#cb131-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'GGally' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: ggplot2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'GGally':
  method from   
  +.gg   ggplot2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb135"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb135-1"><a href="#cb135-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpairs</span>(X)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-58-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The high correlation between age and experience might be the root cause of multicollinearity. Again by looking at the partial correlation coefficient matrix among the variables, it is also clear that the partial correlation between experience – education, age – education and age – experience are quite high.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb136"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb136-1"><a href="#cb136-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(X)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            EDUCATION  EXPERIENCE       WAGE        AGE
EDUCATION   1.0000000 -0.35267645 0.38192207 -0.1500195
EXPERIENCE -0.3526764  1.00000000 0.08705953  0.9779612
WAGE        0.3819221  0.08705953 1.00000000  0.1769669
AGE        -0.1500195  0.97796125 0.17696688  1.0000000</code></pre>
</div>
</div>
<p>If we look at the VIF for the model we can get a sense of how bad it really is. Note that VIF is defined for quantitative variables, so if I use the vif function I will get a “generalized” vif since I have so many categorical predictors. That’s ok. It has the same general interpretation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb138"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb138-1"><a href="#cb138-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(wage.log.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  GVIF Df GVIF^(1/(2*Df))
EDUCATION   234.855660  1       15.325001
SOUTH         1.061343  1        1.030215
SEX           1.272000  1        1.127830
EXPERIENCE 5212.811724  1       72.199804
UNION         1.128802  1        1.062451
AGE        4669.808671  1       68.335998
RACE          1.094538  2        1.022840
OCCUPATION    3.020968  5        1.116901
SECTOR        1.444859  2        1.096368
MARR          1.111966  1        1.054498</code></pre>
</div>
</div>
<p>Education, age and experience all have extremely high VIF measures. This is not surprising.</p>
<p>The simplest remedy for the problem is to remove one of these correlated predictors from the model. Since experience has the highest VIF, let’s remove EXPERIENCE. This can be done by adding <code>-EXPERIENCE</code> to the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb140"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb140-1"><a href="#cb140-1" aria-hidden="true" tabindex="-1"></a>wage.log.fit2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(WAGE) <span class="sc">~</span> . <span class="sc">-</span> EXPERIENCE, <span class="at">data=</span>wages)</span>
<span id="cb140-2"><a href="#cb140-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wage.log.fit2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(WAGE) ~ . - EXPERIENCE, data = wages)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.36094 -0.28111  0.00376  0.27757  1.79529 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.139876   0.186526   6.111 1.95e-09 ***
EDUCATION    0.057206   0.009541   5.996 3.80e-09 ***
SOUTH1      -0.093477   0.041934  -2.229 0.026233 *  
SEX1        -0.216721   0.041846  -5.179 3.20e-07 ***
UNION1       0.211528   0.051224   4.129 4.24e-05 ***
AGE          0.009347   0.001724   5.421 9.10e-08 ***
RACE2       -0.034072   0.099060  -0.344 0.731019    
RACE3        0.079864   0.057397   1.391 0.164692    
OCCUPATION2 -0.364504   0.091508  -3.983 7.77e-05 ***
OCCUPATION3 -0.210472   0.076181  -2.763 0.005935 ** 
OCCUPATION4 -0.384026   0.080997  -4.741 2.75e-06 ***
OCCUPATION5 -0.050349   0.072726  -0.692 0.489054    
OCCUPATION6 -0.265467   0.079977  -3.319 0.000966 ***
SECTOR1      0.114832   0.054868   2.093 0.036846 *  
SECTOR2      0.093247   0.096523   0.966 0.334462    
MARR1        0.062131   0.041037   1.514 0.130629    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4278 on 518 degrees of freedom
Multiple R-squared:  0.3613,    Adjusted R-squared:  0.3428 
F-statistic: 19.53 on 15 and 518 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Notice that now age and education are statistically significant. Also the <span class="math inline">\(R^2\)</span> is still about the same - it’s gone down from .362 to .361. Plus now we can be much more confident in the coefficient estimates.</p>
<p>Let’s check the VIF values to see if that problem has been fixed</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb142"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb142-1"><a href="#cb142-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(wage.log.fit2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               GVIF Df GVIF^(1/(2*Df))
EDUCATION  1.813186  1        1.346546
SOUTH      1.060840  1        1.029971
SEX        1.268426  1        1.126244
UNION      1.128733  1        1.062418
AGE        1.190469  1        1.091086
RACE       1.094327  2        1.022791
OCCUPATION 2.999691  5        1.116112
SECTOR     1.444471  2        1.096294
MARR       1.109491  1        1.053324</code></pre>
</div>
</div>
<p>Yes. We’d really only be concerned if a single VIF value was greater than 10, or if the average was much bigger than 2.5 or so. This is nothing to be concerned with.</p>
<p>Checking other model diagnostics - to make sure our linear regression assumptions are still met</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb144"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb144-1"><a href="#cb144-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wage.log.fit2, <span class="at">which=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-63-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="R09_Multiple_Regression_files/figure-html/unnamed-chunk-63-2.png" class="img-fluid" width="672"></p>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./prediction2.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Prediction (Multiple Linear Regression)</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./mlr_practice.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Multiple Linear Regression Practice</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>